// Package smswebhook provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package smswebhook

import (
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EventNotificationType.
const (
	MessageDeliverFailed    EventNotificationType = "message.deliver.failed"
	MessageDeliverSucceeded EventNotificationType = "message.deliver.succeeded"
)

// Valid indicates whether the value is a known member of the EventNotificationType enum.
func (e EventNotificationType) Valid() bool {
	switch e {
	case MessageDeliverFailed:
		return true
	case MessageDeliverSucceeded:
		return true
	default:
		return false
	}
}

// AdditionalMetadata defines model for AdditionalMetadata.
type AdditionalMetadata map[string]string

// EventNotificationDto defines model for EventNotificationDto.
type EventNotificationDto struct {
	Data      *SmsEntityResponse     `json:"data,omitempty"`
	EventType *EventNotificationType `json:"eventType,omitempty"`
	Metadata  *AdditionalMetadata    `json:"metadata,omitempty"`
}

// EventNotificationType defines model for EventNotificationType.
type EventNotificationType string

// FailedAttempt defines model for FailedAttempt.
type FailedAttempt struct {
	// Reason Reason of failure attempt
	Reason *string `json:"reason,omitempty"`
	Type   string  `json:"type"`
}

// SmsEntityResponse defines model for SmsEntityResponse.
type SmsEntityResponse struct {
	Content     string                         `json:"content"`
	CreatedAt   time.Time                      `json:"createdAt"`
	From        string                         `json:"from"`
	Id          openapi_types.UUID             `json:"id"`
	IsSent      bool                           `json:"isSent"`
	LastAttempt *SmsEntityResponse_LastAttempt `json:"lastAttempt,omitempty"`
	Owner       openapi_types.UUID             `json:"owner"`
	To          string                         `json:"to"`
	UpdatedAt   time.Time                      `json:"updatedAt"`
}

// SmsEntityResponse_LastAttempt defines model for SmsEntityResponse.LastAttempt.
type SmsEntityResponse_LastAttempt struct {
	AttemptCount *int `json:"attemptCount,omitempty"`
	union        json.RawMessage
}

// SuccessfulAttempt defines model for SuccessfulAttempt.
type SuccessfulAttempt struct {
	Type string `json:"type"`
}

// SmsGatewayNotifyJSONRequestBody defines body for SmsGatewayNotify for application/json ContentType.
type SmsGatewayNotifyJSONRequestBody = EventNotificationDto

// AsSuccessfulAttempt returns the union data inside the SmsEntityResponse_LastAttempt as a SuccessfulAttempt
func (t SmsEntityResponse_LastAttempt) AsSuccessfulAttempt() (SuccessfulAttempt, error) {
	var body SuccessfulAttempt
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSuccessfulAttempt overwrites any union data inside the SmsEntityResponse_LastAttempt as the provided SuccessfulAttempt
func (t *SmsEntityResponse_LastAttempt) FromSuccessfulAttempt(v SuccessfulAttempt) error {
	v.Type = "success"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSuccessfulAttempt performs a merge with any union data inside the SmsEntityResponse_LastAttempt, using the provided SuccessfulAttempt
func (t *SmsEntityResponse_LastAttempt) MergeSuccessfulAttempt(v SuccessfulAttempt) error {
	v.Type = "success"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFailedAttempt returns the union data inside the SmsEntityResponse_LastAttempt as a FailedAttempt
func (t SmsEntityResponse_LastAttempt) AsFailedAttempt() (FailedAttempt, error) {
	var body FailedAttempt
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFailedAttempt overwrites any union data inside the SmsEntityResponse_LastAttempt as the provided FailedAttempt
func (t *SmsEntityResponse_LastAttempt) FromFailedAttempt(v FailedAttempt) error {
	v.Type = "failure"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFailedAttempt performs a merge with any union data inside the SmsEntityResponse_LastAttempt, using the provided FailedAttempt
func (t *SmsEntityResponse_LastAttempt) MergeFailedAttempt(v FailedAttempt) error {
	v.Type = "failure"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SmsEntityResponse_LastAttempt) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SmsEntityResponse_LastAttempt) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "failure":
		return t.AsFailedAttempt()
	case "success":
		return t.AsSuccessfulAttempt()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SmsEntityResponse_LastAttempt) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.AttemptCount != nil {
		object["attemptCount"], err = json.Marshal(t.AttemptCount)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'attemptCount': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *SmsEntityResponse_LastAttempt) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["attemptCount"]; found {
		err = json.Unmarshal(raw, &t.AttemptCount)
		if err != nil {
			return fmt.Errorf("error reading 'attemptCount': %w", err)
		}
	}

	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /sms-webhook/notify)
	SmsGatewayNotify(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SmsGatewayNotify operation middleware
func (siw *ServerInterfaceWrapper) SmsGatewayNotify(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SmsGatewayNotify(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/sms-webhook/notify", wrapper.SmsGatewayNotify)
}
