// Package smswebhook provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package smswebhook

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EventNotificationType.
const (
	MessageDeliverFailed    EventNotificationType = "message.deliver.failed"
	MessageDeliverSucceeded EventNotificationType = "message.deliver.succeeded"
)

// Valid indicates whether the value is a known member of the EventNotificationType enum.
func (e EventNotificationType) Valid() bool {
	switch e {
	case MessageDeliverFailed:
		return true
	case MessageDeliverSucceeded:
		return true
	default:
		return false
	}
}

// AdditionalMetadata defines model for AdditionalMetadata.
type AdditionalMetadata map[string]string

// EventNotificationDto defines model for EventNotificationDto.
type EventNotificationDto struct {
	Data      *SmsEntityResponse     `json:"data,omitempty"`
	EventType *EventNotificationType `json:"eventType,omitempty"`
	Metadata  *AdditionalMetadata    `json:"metadata,omitempty"`
}

// EventNotificationType defines model for EventNotificationType.
type EventNotificationType string

// FailedAttempt defines model for FailedAttempt.
type FailedAttempt struct {
	// Reason Reason of failure attempt
	Reason *string `json:"reason,omitempty"`
	Type   string  `json:"type"`
}

// SmsEntityResponse defines model for SmsEntityResponse.
type SmsEntityResponse struct {
	Content     string                         `json:"content"`
	CreatedAt   time.Time                      `json:"createdAt"`
	From        string                         `json:"from"`
	Id          openapi_types.UUID             `json:"id"`
	IsSent      bool                           `json:"isSent"`
	LastAttempt *SmsEntityResponse_LastAttempt `json:"lastAttempt,omitempty"`
	Owner       openapi_types.UUID             `json:"owner"`
	To          string                         `json:"to"`
	UpdatedAt   time.Time                      `json:"updatedAt"`
}

// SmsEntityResponse_LastAttempt defines model for SmsEntityResponse.LastAttempt.
type SmsEntityResponse_LastAttempt struct {
	AttemptCount *int `json:"attemptCount,omitempty"`
	union        json.RawMessage
}

// SuccessfulAttempt defines model for SuccessfulAttempt.
type SuccessfulAttempt struct {
	Type string `json:"type"`
}

// SmsGatewayNotifyJSONRequestBody defines body for SmsGatewayNotify for application/json ContentType.
type SmsGatewayNotifyJSONRequestBody = EventNotificationDto

// AsSuccessfulAttempt returns the union data inside the SmsEntityResponse_LastAttempt as a SuccessfulAttempt
func (t SmsEntityResponse_LastAttempt) AsSuccessfulAttempt() (SuccessfulAttempt, error) {
	var body SuccessfulAttempt
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSuccessfulAttempt overwrites any union data inside the SmsEntityResponse_LastAttempt as the provided SuccessfulAttempt
func (t *SmsEntityResponse_LastAttempt) FromSuccessfulAttempt(v SuccessfulAttempt) error {
	v.Type = "success"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSuccessfulAttempt performs a merge with any union data inside the SmsEntityResponse_LastAttempt, using the provided SuccessfulAttempt
func (t *SmsEntityResponse_LastAttempt) MergeSuccessfulAttempt(v SuccessfulAttempt) error {
	v.Type = "success"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFailedAttempt returns the union data inside the SmsEntityResponse_LastAttempt as a FailedAttempt
func (t SmsEntityResponse_LastAttempt) AsFailedAttempt() (FailedAttempt, error) {
	var body FailedAttempt
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFailedAttempt overwrites any union data inside the SmsEntityResponse_LastAttempt as the provided FailedAttempt
func (t *SmsEntityResponse_LastAttempt) FromFailedAttempt(v FailedAttempt) error {
	v.Type = "failure"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFailedAttempt performs a merge with any union data inside the SmsEntityResponse_LastAttempt, using the provided FailedAttempt
func (t *SmsEntityResponse_LastAttempt) MergeFailedAttempt(v FailedAttempt) error {
	v.Type = "failure"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SmsEntityResponse_LastAttempt) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SmsEntityResponse_LastAttempt) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "failure":
		return t.AsFailedAttempt()
	case "success":
		return t.AsSuccessfulAttempt()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SmsEntityResponse_LastAttempt) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.AttemptCount != nil {
		object["attemptCount"], err = json.Marshal(t.AttemptCount)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'attemptCount': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *SmsEntityResponse_LastAttempt) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["attemptCount"]; found {
		err = json.Unmarshal(raw, &t.AttemptCount)
		if err != nil {
			return fmt.Errorf("error reading 'attemptCount': %w", err)
		}
	}

	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /sms-webhook/notify)
	SmsGatewayNotify(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SmsGatewayNotify operation middleware
func (siw *ServerInterfaceWrapper) SmsGatewayNotify(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SmsGatewayNotify(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/sms-webhook/notify", wrapper.SmsGatewayNotify)
}

type SmsGatewayNotifyRequestObject struct {
	Body *SmsGatewayNotifyJSONRequestBody
}

type SmsGatewayNotifyResponseObject interface {
	VisitSmsGatewayNotifyResponse(w http.ResponseWriter) error
}

type SmsGatewayNotify200Response struct {
}

func (response SmsGatewayNotify200Response) VisitSmsGatewayNotifyResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /sms-webhook/notify)
	SmsGatewayNotify(ctx context.Context, request SmsGatewayNotifyRequestObject) (SmsGatewayNotifyResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// SmsGatewayNotify operation middleware
func (sh *strictHandler) SmsGatewayNotify(ctx *gin.Context) {
	var request SmsGatewayNotifyRequestObject

	var body SmsGatewayNotifyJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SmsGatewayNotify(ctx, request.(SmsGatewayNotifyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SmsGatewayNotify")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(SmsGatewayNotifyResponseObject); ok {
		if err := validResponse.VisitSmsGatewayNotifyResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
