// Package scheduler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package scheduler

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateSchedule defines model for CreateSchedule.
type CreateSchedule struct {
	Data map[string]map[string]interface{} `json:"data"`

	// Route Receiver route
	Route      string    `json:"route"`
	ScheduleAt time.Time `json:"scheduleAt"`
}

// ScheduleId defines model for ScheduleId.
type ScheduleId = openapi_types.UUID

// AddScheduleJSONRequestBody defines body for AddSchedule for application/json ContentType.
type AddScheduleJSONRequestBody = CreateSchedule

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// RemoveSchedule request
	RemoveSchedule(ctx context.Context, scheduleId ScheduleId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddScheduleWithBody request with any body
	AddScheduleWithBody(ctx context.Context, scheduleId ScheduleId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddSchedule(ctx context.Context, scheduleId ScheduleId, body AddScheduleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) RemoveSchedule(ctx context.Context, scheduleId ScheduleId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRemoveScheduleRequest(c.Server, scheduleId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddScheduleWithBody(ctx context.Context, scheduleId ScheduleId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddScheduleRequestWithBody(c.Server, scheduleId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddSchedule(ctx context.Context, scheduleId ScheduleId, body AddScheduleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddScheduleRequest(c.Server, scheduleId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewRemoveScheduleRequest generates requests for RemoveSchedule
func NewRemoveScheduleRequest(server string, scheduleId ScheduleId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "scheduleId", runtime.ParamLocationPath, scheduleId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/schedules/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddScheduleRequest calls the generic AddSchedule builder with application/json body
func NewAddScheduleRequest(server string, scheduleId ScheduleId, body AddScheduleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddScheduleRequestWithBody(server, scheduleId, "application/json", bodyReader)
}

// NewAddScheduleRequestWithBody generates requests for AddSchedule with any type of body
func NewAddScheduleRequestWithBody(server string, scheduleId ScheduleId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "scheduleId", runtime.ParamLocationPath, scheduleId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/schedules/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// RemoveScheduleWithResponse request
	RemoveScheduleWithResponse(ctx context.Context, scheduleId ScheduleId, reqEditors ...RequestEditorFn) (*RemoveScheduleResponse, error)

	// AddScheduleWithBodyWithResponse request with any body
	AddScheduleWithBodyWithResponse(ctx context.Context, scheduleId ScheduleId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddScheduleResponse, error)

	AddScheduleWithResponse(ctx context.Context, scheduleId ScheduleId, body AddScheduleJSONRequestBody, reqEditors ...RequestEditorFn) (*AddScheduleResponse, error)
}

type RemoveScheduleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r RemoveScheduleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RemoveScheduleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddScheduleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *struct {
		ScheduleId *ScheduleId `json:"scheduleId,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r AddScheduleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddScheduleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// RemoveScheduleWithResponse request returning *RemoveScheduleResponse
func (c *ClientWithResponses) RemoveScheduleWithResponse(ctx context.Context, scheduleId ScheduleId, reqEditors ...RequestEditorFn) (*RemoveScheduleResponse, error) {
	rsp, err := c.RemoveSchedule(ctx, scheduleId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRemoveScheduleResponse(rsp)
}

// AddScheduleWithBodyWithResponse request with arbitrary body returning *AddScheduleResponse
func (c *ClientWithResponses) AddScheduleWithBodyWithResponse(ctx context.Context, scheduleId ScheduleId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddScheduleResponse, error) {
	rsp, err := c.AddScheduleWithBody(ctx, scheduleId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddScheduleResponse(rsp)
}

func (c *ClientWithResponses) AddScheduleWithResponse(ctx context.Context, scheduleId ScheduleId, body AddScheduleJSONRequestBody, reqEditors ...RequestEditorFn) (*AddScheduleResponse, error) {
	rsp, err := c.AddSchedule(ctx, scheduleId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddScheduleResponse(rsp)
}

// ParseRemoveScheduleResponse parses an HTTP response from a RemoveScheduleWithResponse call
func ParseRemoveScheduleResponse(rsp *http.Response) (*RemoveScheduleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RemoveScheduleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseAddScheduleResponse parses an HTTP response from a AddScheduleWithResponse call
func ParseAddScheduleResponse(rsp *http.Response) (*AddScheduleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddScheduleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest struct {
			ScheduleId *ScheduleId `json:"scheduleId,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	}

	return response, nil
}
