// Package walletapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package walletapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Customer defines model for Customer.
type Customer struct {
	Email   *openapi_types.Email `json:"email,omitempty"`
	Id      string               `json:"id"`
	Name    string               `json:"name"`
	Phone   *string              `json:"phone,omitempty"`
	Surname string               `json:"surname"`
}

// CustomerId defines model for CustomerId.
type CustomerId = openapi_types.UUID

// GiftCardId defines model for GiftCardId.
type GiftCardId = openapi_types.UUID

// GiftCardMoneyCreditedEvent defines model for GiftCardMoneyCreditedEvent.
type GiftCardMoneyCreditedEvent struct {
	Amount     *float32    `json:"amount,omitempty"`
	At         *time.Time  `json:"at,omitempty"`
	ExpireAt   *time.Time  `json:"expireAt,omitempty"`
	GiftCardId *GiftCardId `json:"giftCardId,omitempty"`
}

// GiftCardMoneyExpiredEvent defines model for GiftCardMoneyExpiredEvent.
type GiftCardMoneyExpiredEvent struct {
	Amount     *float32    `json:"amount,omitempty"`
	At         *time.Time  `json:"at,omitempty"`
	GiftCardId *GiftCardId `json:"giftCardId,omitempty"`
}

// MoneyChargedEvent defines model for MoneyChargedEvent.
type MoneyChargedEvent struct {
	Amount *float32   `json:"amount,omitempty"`
	At     *time.Time `json:"at,omitempty"`
}

// MoneyCreditedEvent defines model for MoneyCreditedEvent.
type MoneyCreditedEvent struct {
	Amount *float32   `json:"amount,omitempty"`
	At     *time.Time `json:"at,omitempty"`
}

// Wallet defines model for Wallet.
type Wallet struct {
	AvailableAmount *float32           `json:"availableAmount,omitempty"`
	CreatedAt       *time.Time         `json:"createdAt,omitempty"`
	Customer        *Customer          `json:"customer,omitempty"`
	History         *[]WalletOperation `json:"history,omitempty"`
	Id              *WalletId          `json:"id,omitempty"`
	Spent           *float32           `json:"spent,omitempty"`
	UpdatedAt       *time.Time         `json:"updatedAt,omitempty"`
}

// WalletId defines model for WalletId.
type WalletId = openapi_types.UUID

// WalletOperation defines model for WalletOperation.
type WalletOperation struct {
	union json.RawMessage
}

// GetWalletsParams defines parameters for GetWallets.
type GetWalletsParams struct {
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// AddGiftCardJSONBody defines parameters for AddGiftCard.
type AddGiftCardJSONBody struct {
	Amount     float32    `json:"amount"`
	CustomerId CustomerId `json:"customerId"`
}

// ChargeWalletJSONBody defines parameters for ChargeWallet.
type ChargeWalletJSONBody struct {
	Amount float32 `json:"amount"`
}

// AddGiftCardJSONRequestBody defines body for AddGiftCard for application/json ContentType.
type AddGiftCardJSONRequestBody AddGiftCardJSONBody

// ChargeWalletJSONRequestBody defines body for ChargeWallet for application/json ContentType.
type ChargeWalletJSONRequestBody ChargeWalletJSONBody

// AsMoneyCreditedEvent returns the union data inside the WalletOperation as a MoneyCreditedEvent
func (t WalletOperation) AsMoneyCreditedEvent() (MoneyCreditedEvent, error) {
	var body MoneyCreditedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMoneyCreditedEvent overwrites any union data inside the WalletOperation as the provided MoneyCreditedEvent
func (t *WalletOperation) FromMoneyCreditedEvent(v MoneyCreditedEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMoneyCreditedEvent performs a merge with any union data inside the WalletOperation, using the provided MoneyCreditedEvent
func (t *WalletOperation) MergeMoneyCreditedEvent(v MoneyCreditedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMoneyChargedEvent returns the union data inside the WalletOperation as a MoneyChargedEvent
func (t WalletOperation) AsMoneyChargedEvent() (MoneyChargedEvent, error) {
	var body MoneyChargedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMoneyChargedEvent overwrites any union data inside the WalletOperation as the provided MoneyChargedEvent
func (t *WalletOperation) FromMoneyChargedEvent(v MoneyChargedEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMoneyChargedEvent performs a merge with any union data inside the WalletOperation, using the provided MoneyChargedEvent
func (t *WalletOperation) MergeMoneyChargedEvent(v MoneyChargedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGiftCardMoneyCreditedEvent returns the union data inside the WalletOperation as a GiftCardMoneyCreditedEvent
func (t WalletOperation) AsGiftCardMoneyCreditedEvent() (GiftCardMoneyCreditedEvent, error) {
	var body GiftCardMoneyCreditedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGiftCardMoneyCreditedEvent overwrites any union data inside the WalletOperation as the provided GiftCardMoneyCreditedEvent
func (t *WalletOperation) FromGiftCardMoneyCreditedEvent(v GiftCardMoneyCreditedEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGiftCardMoneyCreditedEvent performs a merge with any union data inside the WalletOperation, using the provided GiftCardMoneyCreditedEvent
func (t *WalletOperation) MergeGiftCardMoneyCreditedEvent(v GiftCardMoneyCreditedEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGiftCardMoneyExpiredEvent returns the union data inside the WalletOperation as a GiftCardMoneyExpiredEvent
func (t WalletOperation) AsGiftCardMoneyExpiredEvent() (GiftCardMoneyExpiredEvent, error) {
	var body GiftCardMoneyExpiredEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGiftCardMoneyExpiredEvent overwrites any union data inside the WalletOperation as the provided GiftCardMoneyExpiredEvent
func (t *WalletOperation) FromGiftCardMoneyExpiredEvent(v GiftCardMoneyExpiredEvent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGiftCardMoneyExpiredEvent performs a merge with any union data inside the WalletOperation, using the provided GiftCardMoneyExpiredEvent
func (t *WalletOperation) MergeGiftCardMoneyExpiredEvent(v GiftCardMoneyExpiredEvent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t WalletOperation) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *WalletOperation) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /admin/wallets)
	GetWallets(c *gin.Context, params GetWalletsParams)

	// (POST /admin/wallets/giftCard)
	AddGiftCard(c *gin.Context)

	// (GET /admin/wallets/{walletId})
	GetWalletById(c *gin.Context, walletId WalletId)

	// (PUT /admin/wallets/{walletId}/charge)
	ChargeWallet(c *gin.Context, walletId WalletId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetWallets operation middleware
func (siw *ServerInterfaceWrapper) GetWallets(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWalletsParams

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "filter", c.Request.URL.Query(), &params.Filter, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filter: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWallets(c, params)
}

// AddGiftCard operation middleware
func (siw *ServerInterfaceWrapper) AddGiftCard(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddGiftCard(c)
}

// GetWalletById operation middleware
func (siw *ServerInterfaceWrapper) GetWalletById(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "walletId" -------------
	var walletId WalletId

	err = runtime.BindStyledParameterWithOptions("simple", "walletId", c.Param("walletId"), &walletId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter walletId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWalletById(c, walletId)
}

// ChargeWallet operation middleware
func (siw *ServerInterfaceWrapper) ChargeWallet(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "walletId" -------------
	var walletId WalletId

	err = runtime.BindStyledParameterWithOptions("simple", "walletId", c.Param("walletId"), &walletId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter walletId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ChargeWallet(c, walletId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/admin/wallets", wrapper.GetWallets)
	router.POST(options.BaseURL+"/admin/wallets/giftCard", wrapper.AddGiftCard)
	router.GET(options.BaseURL+"/admin/wallets/:walletId", wrapper.GetWalletById)
	router.PUT(options.BaseURL+"/admin/wallets/:walletId/charge", wrapper.ChargeWallet)
}

type GetWalletsRequestObject struct {
	Params GetWalletsParams
}

type GetWalletsResponseObject interface {
	VisitGetWalletsResponse(w http.ResponseWriter) error
}

type GetWallets200JSONResponse []Wallet

func (response GetWallets200JSONResponse) VisitGetWalletsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetWallets400Response struct {
}

func (response GetWallets400Response) VisitGetWalletsResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type AddGiftCardRequestObject struct {
	Body *AddGiftCardJSONRequestBody
}

type AddGiftCardResponseObject interface {
	VisitAddGiftCardResponse(w http.ResponseWriter) error
}

type AddGiftCard200JSONResponse struct {
	Id *WalletId `json:"id,omitempty"`
}

func (response AddGiftCard200JSONResponse) VisitAddGiftCardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AddGiftCard400Response struct {
}

func (response AddGiftCard400Response) VisitAddGiftCardResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetWalletByIdRequestObject struct {
	WalletId WalletId `json:"walletId"`
}

type GetWalletByIdResponseObject interface {
	VisitGetWalletByIdResponse(w http.ResponseWriter) error
}

type GetWalletById200JSONResponse Wallet

func (response GetWalletById200JSONResponse) VisitGetWalletByIdResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetWalletById400Response struct {
}

func (response GetWalletById400Response) VisitGetWalletByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetWalletById404Response struct {
}

func (response GetWalletById404Response) VisitGetWalletByIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ChargeWalletRequestObject struct {
	WalletId WalletId `json:"walletId"`
	Body     *ChargeWalletJSONRequestBody
}

type ChargeWalletResponseObject interface {
	VisitChargeWalletResponse(w http.ResponseWriter) error
}

type ChargeWallet200JSONResponse struct {
	Id *WalletId `json:"id,omitempty"`
}

func (response ChargeWallet200JSONResponse) VisitChargeWalletResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /admin/wallets)
	GetWallets(ctx context.Context, request GetWalletsRequestObject) (GetWalletsResponseObject, error)

	// (POST /admin/wallets/giftCard)
	AddGiftCard(ctx context.Context, request AddGiftCardRequestObject) (AddGiftCardResponseObject, error)

	// (GET /admin/wallets/{walletId})
	GetWalletById(ctx context.Context, request GetWalletByIdRequestObject) (GetWalletByIdResponseObject, error)

	// (PUT /admin/wallets/{walletId}/charge)
	ChargeWallet(ctx context.Context, request ChargeWalletRequestObject) (ChargeWalletResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetWallets operation middleware
func (sh *strictHandler) GetWallets(ctx *gin.Context, params GetWalletsParams) {
	var request GetWalletsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWallets(ctx, request.(GetWalletsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWallets")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetWalletsResponseObject); ok {
		if err := validResponse.VisitGetWalletsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddGiftCard operation middleware
func (sh *strictHandler) AddGiftCard(ctx *gin.Context) {
	var request AddGiftCardRequestObject

	var body AddGiftCardJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AddGiftCard(ctx, request.(AddGiftCardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddGiftCard")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AddGiftCardResponseObject); ok {
		if err := validResponse.VisitAddGiftCardResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWalletById operation middleware
func (sh *strictHandler) GetWalletById(ctx *gin.Context, walletId WalletId) {
	var request GetWalletByIdRequestObject

	request.WalletId = walletId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWalletById(ctx, request.(GetWalletByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWalletById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetWalletByIdResponseObject); ok {
		if err := validResponse.VisitGetWalletByIdResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ChargeWallet operation middleware
func (sh *strictHandler) ChargeWallet(ctx *gin.Context, walletId WalletId) {
	var request ChargeWalletRequestObject

	request.WalletId = walletId

	var body ChargeWalletJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ChargeWallet(ctx, request.(ChargeWalletRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChargeWallet")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ChargeWalletResponseObject); ok {
		if err := validResponse.VisitChargeWalletResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
