// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ExternalIdentity struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
	UserID   string `json:"user_id"`
}

type Membership struct {
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
	Active         bool   `json:"active"`
}

type MembershipRole struct {
	MembershipID string `json:"membership_id"`
	RoleID       string `json:"role_id"`
}

type Organization struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Permission struct {
	ID   string `json:"id"`
	Code string `json:"code"`
}

type Role struct {
	ID             string      `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
}

type RolePermission struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
}

type User struct {
	ID    string      `json:"id"`
	Email pgtype.Text `json:"email"`
}
