// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package queries

import (
	"context"
)

const createExternalIdentity = `-- name: CreateExternalIdentity :exec
INSERT INTO external_identities (provider,subject,user_id) VALUES ($1,$2,$3)
`

type CreateExternalIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
	UserID   string `json:"user_id"`
}

func (q *Queries) CreateExternalIdentity(ctx context.Context, arg CreateExternalIdentityParams) error {
	_, err := q.db.Exec(ctx, createExternalIdentity, arg.Provider, arg.Subject, arg.UserID)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id,email) VALUES ($1,NULLIF($2,''))
`

type CreateUserParams struct {
	ID      string      `json:"id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.ID, arg.Column2)
	return err
}

const findMembership = `-- name: FindMembership :one
SELECT id::text,user_id::text,organization_id::text,active FROM memberships WHERE user_id=$1 AND organization_id=$2
`

type FindMembershipParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
}

type FindMembershipRow struct {
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
	Active         bool   `json:"active"`
}

func (q *Queries) FindMembership(ctx context.Context, arg FindMembershipParams) (FindMembershipRow, error) {
	row := q.db.QueryRow(ctx, findMembership, arg.UserID, arg.OrganizationID)
	var i FindMembershipRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.Active,
	)
	return i, err
}

const findUserByExternalIdentity = `-- name: FindUserByExternalIdentity :one
SELECT u.id::text, coalesce(u.email,'') AS email FROM external_identities e JOIN users u ON u.id=e.user_id WHERE e.provider=$1 AND e.subject=$2
`

type FindUserByExternalIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

type FindUserByExternalIdentityRow struct {
	UID   string `json:"u_id"`
	Email string `json:"email"`
}

func (q *Queries) FindUserByExternalIdentity(ctx context.Context, arg FindUserByExternalIdentityParams) (FindUserByExternalIdentityRow, error) {
	row := q.db.QueryRow(ctx, findUserByExternalIdentity, arg.Provider, arg.Subject)
	var i FindUserByExternalIdentityRow
	err := row.Scan(&i.UID, &i.Email)
	return i, err
}

const grantRolePermission = `-- name: GrantRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type GrantRolePermissionParams struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
}

func (q *Queries) GrantRolePermission(ctx context.Context, arg GrantRolePermissionParams) error {
	_, err := q.db.Exec(ctx, grantRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const listMembershipPermissions = `-- name: ListMembershipPermissions :many
SELECT DISTINCT p.code FROM membership_roles mr JOIN role_permissions rp ON rp.role_id=mr.role_id JOIN permissions p ON p.id=rp.permission_id WHERE mr.membership_id=$1 ORDER BY p.code
`

func (q *Queries) ListMembershipPermissions(ctx context.Context, membershipID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listMembershipPermissions, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipRoles = `-- name: ListMembershipRoles :many
SELECT r.name FROM membership_roles mr JOIN roles r ON r.id=mr.role_id WHERE mr.membership_id=$1 ORDER BY r.name
`

func (q *Queries) ListMembershipRoles(ctx context.Context, membershipID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listMembershipRoles, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGlobalRole = `-- name: UpsertGlobalRole :one
INSERT INTO roles (id, organization_id, name) VALUES ($1, NULL, $2) ON CONFLICT (organization_id, name) DO UPDATE SET name = EXCLUDED.name RETURNING id::text
`

type UpsertGlobalRoleParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpsertGlobalRole(ctx context.Context, arg UpsertGlobalRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertGlobalRole, arg.ID, arg.Name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertPermission = `-- name: UpsertPermission :one
INSERT INTO permissions (id, code) VALUES ($1, $2) ON CONFLICT (code) DO UPDATE SET code = EXCLUDED.code RETURNING id::text
`

type UpsertPermissionParams struct {
	ID   string `json:"id"`
	Code string `json:"code"`
}

func (q *Queries) UpsertPermission(ctx context.Context, arg UpsertPermissionParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertPermission, arg.ID, arg.Code)
	var id string
	err := row.Scan(&id)
	return id, err
}
