apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appointment-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: oci-vault-backend
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  refreshInterval: 24h
  target:
    name: appointment-secrets
    creationPolicy: Owner
    template:
      data:
        postgres-dsn: "postgres://{{ `{{ .username }}` }}:{{ `{{ .password }}` }}@postgres-rw.common.svc.cluster.local:5432/appointments?sslmode=disable"
        MONGO_DB_URI: "{{ `{{ .mongoUri }}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: beaesthetic-postgres
        property: username
    - secretKey: password
      remoteRef:
        key: beaesthetic-postgres
        property: password
    - secretKey: mongoUri
      remoteRef:
        key: appointment-secrets
        property: MONGO_DB_URI
