apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appointment-rabbitmq-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: oci-vault-backend
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  refreshInterval: 24h
  target:
    name: appointment-rabbitmq-secrets
    creationPolicy: Owner
    template:
      data:
        rabbitmq-password: "{{ `{{ .rabbitmqPassword }}` }}"
  data:
    - secretKey: rabbitmqPassword
      remoteRef:
        key: rabbitmq-credentials
        property: password