// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateSchedule defines model for CreateSchedule.
type CreateSchedule struct {
	Data map[string]interface{} `json:"data"`

	// Route Receiver route
	Route      string    `json:"route"`
	ScheduleAt time.Time `json:"scheduleAt"`
}

// ScheduleId defines model for ScheduleId.
type ScheduleId = openapi_types.UUID

// AddScheduleJSONRequestBody defines body for AddSchedule for application/json ContentType.
type AddScheduleJSONRequestBody = CreateSchedule

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (DELETE /schedules/{scheduleId})
	RemoveSchedule(c *gin.Context, scheduleId ScheduleId)

	// (PUT /schedules/{scheduleId})
	AddSchedule(c *gin.Context, scheduleId ScheduleId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// RemoveSchedule operation middleware
func (siw *ServerInterfaceWrapper) RemoveSchedule(c *gin.Context) {

	var err error

	// ------------- Path parameter "scheduleId" -------------
	var scheduleId ScheduleId

	err = runtime.BindStyledParameterWithOptions("simple", "scheduleId", c.Param("scheduleId"), &scheduleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scheduleId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveSchedule(c, scheduleId)
}

// AddSchedule operation middleware
func (siw *ServerInterfaceWrapper) AddSchedule(c *gin.Context) {

	var err error

	// ------------- Path parameter "scheduleId" -------------
	var scheduleId ScheduleId

	err = runtime.BindStyledParameterWithOptions("simple", "scheduleId", c.Param("scheduleId"), &scheduleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter scheduleId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddSchedule(c, scheduleId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.DELETE(options.BaseURL+"/schedules/:scheduleId", wrapper.RemoveSchedule)
	router.PUT(options.BaseURL+"/schedules/:scheduleId", wrapper.AddSchedule)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RUsW7bMBD9FeHaUZFcN5OmukEGA0URJGPggSHPFg2JZMiTjcDgvxdHWbFUuWg6dZJA",
	"8u69e++RJ5C2ddagoQDVCYKssRXp986jIHySNaquQV5x3jr0pDHtK0GCv0IpTdoa0TyM9sl3mAO9OYQK",
	"7MseJUHMwduOUi+FQXrtuBAqeESJ+oA+6/ffCwN5bXZcGM48VsTVW+tbQVAxCbwh3V6pYTR87bRHBdXz",
	"uEHecx/YbK7wHMZeqwlc12l1BSnmoM3W8lFpDQmZSGIrdAMVOCSPpIVRHsW3Ha8W0rYMM1VhAPXZ6mEN",
	"OTRaoglJLiNaRlw5IWvMlsUCcug8d6+JXFWWx+OxEGm3sH5XnktD+WN9d//z6f5mWSyKmtqGUUkTGzrD",
	"O6APPZMvxaJY8FHr0AinoYKvaSkHJ6hO/peDoqE8hXe5Ym9ug73NHAjB47GQ8IitPVwixc28aJHQB6ie",
	"T6AZmwEgHya+dIaxn328+rQyzmePW6jgU3mJc3nOcjnyMsYNdwnOsjhcuFzczuM4VGR7+5L1wyhW4/av",
	"h42lbGs7o1L+SOzCOHsBNjEH19FcmpVS/1+X1w4DfbfqbUgymkRVONdomciW+8BTnz6I8dsjEqe3ktnG",
	"mSHLf0KfPkphcm8/PP3sBYizy7mSEh2hysLI7z+6HGP8FQAA//9uczcRWwUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
