apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: identity-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: oci-vault-backend
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: 24h
  target:
    name: identity-secrets
    creationPolicy: Owner
    template:
      data:
        ENV_POSTGRES_DSN: "postgres://{{ `{{ .username }}` }}:{{ `{{ .password }}` }}@postgres-rw.common.svc.cluster.local:5432/beaesthetic-prod-identity-service?sslmode=disable"
        ENV_TOKEN_ACTIVE_KEY_ID: "{{ `{{ .tokenActiveKeyId }}` }}"
        ENV_TOKEN_PRIVATE_KEY_B64: "{{ `{{ .tokenPrivateKeyB64 }}` }}"
        ENV_TOKEN_VERIFY_KEYS_JSON: "{{ `{{ .tokenVerifyKeysJson }}` }}"
        ENV_INTERNAL_API_KEY: "{{ `{{ .internalApiKey }}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: beaesthetic-postgres
        property: username
    - secretKey: password
      remoteRef:
        key: beaesthetic-postgres
        property: password
    - secretKey: tokenActiveKeyId
      remoteRef:
        key: beaesthetic-identity
        property: tokenActiveKeyId
    - secretKey: tokenPrivateKeyB64
      remoteRef:
        key: beaesthetic-identity
        property: tokenPrivateKeyB64
    - secretKey: tokenVerifyKeysJson
      remoteRef:
        key: beaesthetic-identity
        property: tokenVerifyKeysJson
    - secretKey: internalApiKey
      remoteRef:
        key: beaesthetic-identity
        property: internalApiKey
