{{- if not (include "notification.environment" .) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "notification.commonLabels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: oci-vault-backend
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: 24h
  target:
    name: notification-service
    creationPolicy: Owner
  data:
    - secretKey: MONGO_DB_URI
      remoteRef:
        key: notification-service
        property: MONGO_DB_URI
    - secretKey: SMS_GATEWAY_API_KEY
      remoteRef:
        key: notification-service
        property: SMS_GATEWAY_API_KEY
{{- end }}

