apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: oci-vault-backend
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  refreshInterval: 24h
  target:
    name: notification-secrets
    creationPolicy: Owner
    template:
      data:
        postgres-dsn: "postgres://{{ `{{ .username }}` }}:{{ `{{ .password }}` }}@postgres-rw.common.svc.cluster.local:5432/notifications?sslmode=disable"
        rabbitmq-password: "{{ `{{ .rabbitmqPassword }}` }}"
        rabbitmq-url: "amqp://beaesthetic:{{ `{{ .rabbitmqPassword }}` }}@rabbitmq-v2.common.svc.cluster.local:5672/"
  data:
    - secretKey: username
      remoteRef:
        key: beaesthetic-postgres
        property: username
    - secretKey: password
      remoteRef:
        key: beaesthetic-postgres
        property: password
    - secretKey: rabbitmqPassword
      remoteRef:
        key: rabbitmq-credentials
        property: password
