apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-outbox-config"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "notification.commonLabels" . | nindent 4 }}
data:
  outbox.yaml: |-
    source:
      type: postgres
      data:
        dsn: ${POSTGRES_DSN}
        table_name: outbox_messages
        batch_size: 100
        poll_interval: 1s
        initialize_schema: true

    channels:
      - name: customer.notifications.outcomes
        publisher:
          type: rabbitmq
          data:
            url: ${RABBITMQ_DSN}
            exchange: beaesthetic.notifications
            routing_key: ${RABBITMQ__CUSTOMER_NOTIFICATION_OUTCOMES_ROUTING_KEY}
            content_type: application/json
