apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-connection-uri-consents
  namespace: beaesthetic
spec:
  secretStoreRef:
    name: oci-vault-backend
    kind: ClusterSecretStore

  refreshPolicy: CreatedOnce
  refreshInterval: 24h
  target:
    name: mongodb-connection-uri-consents
    creationPolicy: Owner
    template:
      type: Opaque

  data:
    - secretKey: CONSENT_MONGODB_CONNECTION_STRING
      remoteRef:
        key: keyvault/data/beaesthetic/mongodb_connection_string
        property: uri
