apiVersion: v1
kind: Service
metadata:
  name: beaesthetic-consent-service
  namespace: beaesthetic
spec:
  selector:
    app: beaesthetic-consent-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080