// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agenda_events.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAgendaEvent = `-- name: FindAgendaEvent :one
SELECT id,
       event_type,
       title,
       description,
       start_at,
       end_at,
       attendee_id,
       attendee_display_name,
       services,
       cancel_reason,
       reminder_status,
       reminder_sent_at,
       remind_before_seconds,
       version,
       created_at,
       updated_at
FROM agenda_events
WHERE id = $1
`

type FindAgendaEventRow struct {
	ID                  string             `json:"id"`
	EventType           string             `json:"event_type"`
	Title               string             `json:"title"`
	Description         string             `json:"description"`
	StartAt             pgtype.Timestamptz `json:"start_at"`
	EndAt               pgtype.Timestamptz `json:"end_at"`
	AttendeeID          string             `json:"attendee_id"`
	AttendeeDisplayName string             `json:"attendee_display_name"`
	Services            json.RawMessage    `json:"services"`
	CancelReason        pgtype.Text        `json:"cancel_reason"`
	ReminderStatus      string             `json:"reminder_status"`
	ReminderSentAt      pgtype.Timestamptz `json:"reminder_sent_at"`
	RemindBeforeSeconds int32              `json:"remind_before_seconds"`
	Version             int64              `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FindAgendaEvent(ctx context.Context, id string) (FindAgendaEventRow, error) {
	row := q.db.QueryRow(ctx, findAgendaEvent, id)
	var i FindAgendaEventRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Title,
		&i.Description,
		&i.StartAt,
		&i.EndAt,
		&i.AttendeeID,
		&i.AttendeeDisplayName,
		&i.Services,
		&i.CancelReason,
		&i.ReminderStatus,
		&i.ReminderSentAt,
		&i.RemindBeforeSeconds,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findFutureAppointmentIDs = `-- name: FindFutureAppointmentIDs :many
SELECT id
FROM agenda_events
WHERE cancel_reason IS NULL
  AND event_type = $1
  AND start_at >= $2
ORDER BY start_at ASC
`

type FindFutureAppointmentIDsParams struct {
	EventType string             `json:"event_type"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
}

func (q *Queries) FindFutureAppointmentIDs(ctx context.Context, arg FindFutureAppointmentIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, findFutureAppointmentIDs, arg.EventType, arg.StartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAgendaEvent = `-- name: SaveAgendaEvent :exec
INSERT INTO agenda_events (
    id,
    event_type,
    title,
    description,
    display_title,
    display_description,
    start_at,
    end_at,
    attendee_id,
    attendee_display_name,
    services,
    cancel_reason,
    canceled_at,
    reminder_status,
    reminder_sent_at,
    remind_before_seconds,
    version,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, 1, $15, $16
)
ON CONFLICT (id) DO UPDATE SET
    event_type = $2,
    title = $3,
    description = $4,
    display_title = $3,
    display_description = $4,
    start_at = $5,
    end_at = $6,
    attendee_id = $7,
    attendee_display_name = $8,
    services = $9,
    cancel_reason = $10,
    canceled_at = $11,
    reminder_status = $12,
    reminder_sent_at = $13,
    remind_before_seconds = $14,
    version = agenda_events.version + 1,
    updated_at = $16
`

type SaveAgendaEventParams struct {
	ID                  string             `json:"id"`
	EventType           string             `json:"event_type"`
	Title               string             `json:"title"`
	Description         string             `json:"description"`
	StartAt             pgtype.Timestamptz `json:"start_at"`
	EndAt               pgtype.Timestamptz `json:"end_at"`
	AttendeeID          string             `json:"attendee_id"`
	AttendeeDisplayName string             `json:"attendee_display_name"`
	Services            json.RawMessage    `json:"services"`
	CancelReason        pgtype.Text        `json:"cancel_reason"`
	CanceledAt          pgtype.Timestamptz `json:"canceled_at"`
	ReminderStatus      string             `json:"reminder_status"`
	ReminderSentAt      pgtype.Timestamptz `json:"reminder_sent_at"`
	RemindBeforeSeconds int32              `json:"remind_before_seconds"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SaveAgendaEvent(ctx context.Context, arg SaveAgendaEventParams) error {
	_, err := q.db.Exec(ctx, saveAgendaEvent,
		arg.ID,
		arg.EventType,
		arg.Title,
		arg.Description,
		arg.StartAt,
		arg.EndAt,
		arg.AttendeeID,
		arg.AttendeeDisplayName,
		arg.Services,
		arg.CancelReason,
		arg.CanceledAt,
		arg.ReminderStatus,
		arg.ReminderSentAt,
		arg.RemindBeforeSeconds,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const searchAgendaEventIDs = `-- name: SearchAgendaEventIDs :many
SELECT id
FROM agenda_events
WHERE cancel_reason IS NULL
  AND ($1::boolean = false OR attendee_id = $2::text)
  AND ($3::boolean = false OR (start_at >= $4::timestamptz AND start_at <= $5::timestamptz))
ORDER BY start_at ASC
`

type SearchAgendaEventIDsParams struct {
	FilterAttendee  bool               `json:"filter_attendee"`
	AttendeeID      string             `json:"attendee_id"`
	FilterTimeRange bool               `json:"filter_time_range"`
	StartAt         pgtype.Timestamptz `json:"start_at"`
	EndAt           pgtype.Timestamptz `json:"end_at"`
}

func (q *Queries) SearchAgendaEventIDs(ctx context.Context, arg SearchAgendaEventIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, searchAgendaEventIDs,
		arg.FilterAttendee,
		arg.AttendeeID,
		arg.FilterTimeRange,
		arg.StartAt,
		arg.EndAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
