// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agenda_event_details.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAppointmentServiceItems = `-- name: DeleteAppointmentServiceItems :exec
DELETE FROM appointment_service_items
WHERE agenda_event_id = $1
`

func (q *Queries) DeleteAppointmentServiceItems(ctx context.Context, agendaEventID string) error {
	_, err := q.db.Exec(ctx, deleteAppointmentServiceItems, agendaEventID)
	return err
}

const findAgendaEventFromDetails = `-- name: FindAgendaEventFromDetails :one
SELECT
    e.id,
    e.calendar_id,
    e.event_type,
    e.title AS legacy_title,
    e.description AS legacy_description,
    e.start_at,
    e.end_at,
    e.timezone,
    e.all_day,
    e.display_title,
    e.display_description,
    e.visibility,
    e.cancel_reason,
    e.canceled_at,
    e.version,
    e.created_at,
    e.updated_at,
    CASE WHEN a.agenda_event_id IS NULL THEN '' ELSE a.agenda_event_id::text END AS agenda_event_id,
    CASE WHEN a.customer_id IS NULL THEN '' ELSE a.customer_id::text END AS customer_id,
    a.customer_display_name,
    m.title AS manual_title,
    m.description AS manual_description,
    m.location AS manual_location,
    tb.reason AS time_block_reason,
    r.status AS reminder_status,
    r.remind_before_seconds,
    r.scheduled_at AS reminder_scheduled_at,
    r.sent_requested_at AS reminder_sent_requested_at,
    r.sent_at AS reminder_sent_at,
    r.failed_at AS reminder_failed_at,
    r.failure_reason AS reminder_failure_reason,
    r.updated_at AS reminder_updated_at,
    coalesce(
        jsonb_agg(
            jsonb_build_object(
                'Name', si.service_name,
                'serviceId', si.service_id,
                'price', si.price,
                'position', si.position
            )
            ORDER BY si.position
        ) FILTER (WHERE si.agenda_event_id IS NOT NULL),
        '[]'::jsonb
    )::text AS services_json
FROM agenda_events e
LEFT JOIN appointments a ON a.agenda_event_id = e.id
LEFT JOIN agenda_manual_events m ON m.agenda_event_id = e.id
LEFT JOIN agenda_time_blocks tb ON tb.agenda_event_id = e.id
LEFT JOIN appointment_reminders r ON r.agenda_event_id = a.agenda_event_id
LEFT JOIN appointment_service_items si ON si.agenda_event_id = a.agenda_event_id
WHERE e.id = $1
GROUP BY
    e.id,
    e.calendar_id,
    e.event_type,
    e.title,
    e.description,
    e.start_at,
    e.end_at,
    e.timezone,
    e.all_day,
    e.display_title,
    e.display_description,
    e.visibility,
    e.cancel_reason,
    e.canceled_at,
    e.version,
    e.created_at,
    e.updated_at,
    a.agenda_event_id,
    a.customer_id,
    a.customer_display_name,
    m.title,
    m.description,
    m.location,
    tb.reason,
    r.status,
    r.remind_before_seconds,
    r.scheduled_at,
    r.sent_requested_at,
    r.sent_at,
    r.failed_at,
    r.failure_reason,
    r.updated_at
`

type FindAgendaEventFromDetailsRow struct {
	ID                      string             `json:"id"`
	CalendarID              string             `json:"calendar_id"`
	EventType               string             `json:"event_type"`
	LegacyTitle             string             `json:"legacy_title"`
	LegacyDescription       string             `json:"legacy_description"`
	StartAt                 pgtype.Timestamptz `json:"start_at"`
	EndAt                   pgtype.Timestamptz `json:"end_at"`
	Timezone                string             `json:"timezone"`
	AllDay                  bool               `json:"all_day"`
	DisplayTitle            pgtype.Text        `json:"display_title"`
	DisplayDescription      pgtype.Text        `json:"display_description"`
	Visibility              string             `json:"visibility"`
	CancelReason            pgtype.Text        `json:"cancel_reason"`
	CanceledAt              pgtype.Timestamptz `json:"canceled_at"`
	Version                 int64              `json:"version"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	AgendaEventID           string             `json:"agenda_event_id"`
	CustomerID              string             `json:"customer_id"`
	CustomerDisplayName     pgtype.Text        `json:"customer_display_name"`
	ManualTitle             pgtype.Text        `json:"manual_title"`
	ManualDescription       pgtype.Text        `json:"manual_description"`
	ManualLocation          pgtype.Text        `json:"manual_location"`
	TimeBlockReason         pgtype.Text        `json:"time_block_reason"`
	ReminderStatus          pgtype.Text        `json:"reminder_status"`
	RemindBeforeSeconds     pgtype.Int4        `json:"remind_before_seconds"`
	ReminderScheduledAt     pgtype.Timestamptz `json:"reminder_scheduled_at"`
	ReminderSentRequestedAt pgtype.Timestamptz `json:"reminder_sent_requested_at"`
	ReminderSentAt          pgtype.Timestamptz `json:"reminder_sent_at"`
	ReminderFailedAt        pgtype.Timestamptz `json:"reminder_failed_at"`
	ReminderFailureReason   pgtype.Text        `json:"reminder_failure_reason"`
	ReminderUpdatedAt       pgtype.Timestamptz `json:"reminder_updated_at"`
	ServicesJson            string             `json:"services_json"`
}

func (q *Queries) FindAgendaEventFromDetails(ctx context.Context, id string) (FindAgendaEventFromDetailsRow, error) {
	row := q.db.QueryRow(ctx, findAgendaEventFromDetails, id)
	var i FindAgendaEventFromDetailsRow
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.EventType,
		&i.LegacyTitle,
		&i.LegacyDescription,
		&i.StartAt,
		&i.EndAt,
		&i.Timezone,
		&i.AllDay,
		&i.DisplayTitle,
		&i.DisplayDescription,
		&i.Visibility,
		&i.CancelReason,
		&i.CanceledAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgendaEventID,
		&i.CustomerID,
		&i.CustomerDisplayName,
		&i.ManualTitle,
		&i.ManualDescription,
		&i.ManualLocation,
		&i.TimeBlockReason,
		&i.ReminderStatus,
		&i.RemindBeforeSeconds,
		&i.ReminderScheduledAt,
		&i.ReminderSentRequestedAt,
		&i.ReminderSentAt,
		&i.ReminderFailedAt,
		&i.ReminderFailureReason,
		&i.ReminderUpdatedAt,
		&i.ServicesJson,
	)
	return i, err
}

const findAppointmentNotification = `-- name: FindAppointmentNotification :one
SELECT
    n.correlation_key,
    a.agenda_event_id,
    n.notification_kind,
    n.notification_type,
    n.status,
    n.recipient_type,
    n.recipient_id,
    n.notification_idempotency_key,
    n.failure_reason,
    n.failure_message,
    n.created_at,
    n.completed_at,
    n.expires_at
FROM appointment_notifications n
JOIN appointments a ON a.agenda_event_id = n.agenda_event_id
WHERE n.correlation_key = $1
`

type FindAppointmentNotificationRow struct {
	CorrelationKey             string             `json:"correlation_key"`
	AgendaEventID              string             `json:"agenda_event_id"`
	NotificationKind           string             `json:"notification_kind"`
	NotificationType           string             `json:"notification_type"`
	Status                     string             `json:"status"`
	RecipientType              string             `json:"recipient_type"`
	RecipientID                string             `json:"recipient_id"`
	NotificationIdempotencyKey pgtype.Text        `json:"notification_idempotency_key"`
	FailureReason              pgtype.Text        `json:"failure_reason"`
	FailureMessage             pgtype.Text        `json:"failure_message"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	CompletedAt                pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt                  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) FindAppointmentNotification(ctx context.Context, correlationKey string) (FindAppointmentNotificationRow, error) {
	row := q.db.QueryRow(ctx, findAppointmentNotification, correlationKey)
	var i FindAppointmentNotificationRow
	err := row.Scan(
		&i.CorrelationKey,
		&i.AgendaEventID,
		&i.NotificationKind,
		&i.NotificationType,
		&i.Status,
		&i.RecipientType,
		&i.RecipientID,
		&i.NotificationIdempotencyKey,
		&i.FailureReason,
		&i.FailureMessage,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findFutureAppointmentAgendaEventIDsFromDetails = `-- name: FindFutureAppointmentAgendaEventIDsFromDetails :many
SELECT e.id
FROM agenda_events e
JOIN appointments a ON a.agenda_event_id = e.id
WHERE e.canceled_at IS NULL
  AND e.start_at >= $1
ORDER BY e.start_at ASC, e.end_at ASC
`

func (q *Queries) FindFutureAppointmentAgendaEventIDsFromDetails(ctx context.Context, startAt pgtype.Timestamptz) ([]string, error) {
	rows, err := q.db.Query(ctx, findFutureAppointmentAgendaEventIDsFromDetails, startAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAppointmentNotificationFailed = `-- name: MarkAppointmentNotificationFailed :exec
UPDATE appointment_notifications
SET status = 'failed',
    failure_reason = $2,
    failure_message = $3,
    completed_at = $4
WHERE correlation_key = $1
`

type MarkAppointmentNotificationFailedParams struct {
	CorrelationKey string             `json:"correlation_key"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	FailureMessage pgtype.Text        `json:"failure_message"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) MarkAppointmentNotificationFailed(ctx context.Context, arg MarkAppointmentNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markAppointmentNotificationFailed,
		arg.CorrelationKey,
		arg.FailureReason,
		arg.FailureMessage,
		arg.CompletedAt,
	)
	return err
}

const markAppointmentNotificationSent = `-- name: MarkAppointmentNotificationSent :exec
UPDATE appointment_notifications
SET status = 'sent',
    failure_reason = NULL,
    failure_message = NULL,
    completed_at = $2
WHERE correlation_key = $1
`

type MarkAppointmentNotificationSentParams struct {
	CorrelationKey string             `json:"correlation_key"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) MarkAppointmentNotificationSent(ctx context.Context, arg MarkAppointmentNotificationSentParams) error {
	_, err := q.db.Exec(ctx, markAppointmentNotificationSent, arg.CorrelationKey, arg.CompletedAt)
	return err
}

const saveAgendaEventV2 = `-- name: SaveAgendaEventV2 :exec
INSERT INTO agenda_events (
    id,
    calendar_id,
    event_type,
    title,
    description,
    start_at,
    end_at,
    timezone,
    all_day,
    display_title,
    display_description,
    visibility,
    attendee_id,
    attendee_display_name,
    services,
    cancel_reason,
    canceled_at,
    reminder_status,
    reminder_sent_at,
    remind_before_seconds,
    version,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, '[]'::jsonb, $15, $16, 'PENDING', NULL, 0, 1, $17, $18
)
ON CONFLICT (id) DO UPDATE SET
    calendar_id = $2,
    event_type = $3,
    title = $4,
    description = $5,
    start_at = $6,
    end_at = $7,
    timezone = $8,
    all_day = $9,
    display_title = $10,
    display_description = $11,
    visibility = $12,
    attendee_id = $13,
    attendee_display_name = $14,
    cancel_reason = $15,
    canceled_at = $16,
    version = agenda_events.version + 1,
    updated_at = $18
`

type SaveAgendaEventV2Params struct {
	ID                  string             `json:"id"`
	CalendarID          string             `json:"calendar_id"`
	EventType           string             `json:"event_type"`
	Title               string             `json:"title"`
	Description         string             `json:"description"`
	StartAt             pgtype.Timestamptz `json:"start_at"`
	EndAt               pgtype.Timestamptz `json:"end_at"`
	Timezone            string             `json:"timezone"`
	AllDay              bool               `json:"all_day"`
	DisplayTitle        pgtype.Text        `json:"display_title"`
	DisplayDescription  pgtype.Text        `json:"display_description"`
	Visibility          string             `json:"visibility"`
	AttendeeID          string             `json:"attendee_id"`
	AttendeeDisplayName string             `json:"attendee_display_name"`
	CancelReason        pgtype.Text        `json:"cancel_reason"`
	CanceledAt          pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SaveAgendaEventV2(ctx context.Context, arg SaveAgendaEventV2Params) error {
	_, err := q.db.Exec(ctx, saveAgendaEventV2,
		arg.ID,
		arg.CalendarID,
		arg.EventType,
		arg.Title,
		arg.Description,
		arg.StartAt,
		arg.EndAt,
		arg.Timezone,
		arg.AllDay,
		arg.DisplayTitle,
		arg.DisplayDescription,
		arg.Visibility,
		arg.AttendeeID,
		arg.AttendeeDisplayName,
		arg.CancelReason,
		arg.CanceledAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const saveAgendaManualEvent = `-- name: SaveAgendaManualEvent :exec
INSERT INTO agenda_manual_events (
    agenda_event_id,
    title,
    description,
    location,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (agenda_event_id) DO UPDATE SET
    title = $2,
    description = $3,
    location = $4,
    updated_at = $6
`

type SaveAgendaManualEventParams struct {
	AgendaEventID string             `json:"agenda_event_id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Location      pgtype.Text        `json:"location"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SaveAgendaManualEvent(ctx context.Context, arg SaveAgendaManualEventParams) error {
	_, err := q.db.Exec(ctx, saveAgendaManualEvent,
		arg.AgendaEventID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const saveAgendaTimeBlock = `-- name: SaveAgendaTimeBlock :exec
INSERT INTO agenda_time_blocks (
    agenda_event_id,
    reason,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (agenda_event_id) DO UPDATE SET
    reason = $2,
    updated_at = $4
`

type SaveAgendaTimeBlockParams struct {
	AgendaEventID string             `json:"agenda_event_id"`
	Reason        string             `json:"reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SaveAgendaTimeBlock(ctx context.Context, arg SaveAgendaTimeBlockParams) error {
	_, err := q.db.Exec(ctx, saveAgendaTimeBlock,
		arg.AgendaEventID,
		arg.Reason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const saveAppointment = `-- name: SaveAppointment :exec
INSERT INTO appointments (
    agenda_event_id,
    customer_id,
    customer_display_name,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (agenda_event_id) DO UPDATE SET
    customer_id = $2,
    customer_display_name = $3,
    updated_at = $5
`

type SaveAppointmentParams struct {
	AgendaEventID       string             `json:"agenda_event_id"`
	CustomerID          string             `json:"customer_id"`
	CustomerDisplayName string             `json:"customer_display_name"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SaveAppointment(ctx context.Context, arg SaveAppointmentParams) error {
	_, err := q.db.Exec(ctx, saveAppointment,
		arg.AgendaEventID,
		arg.CustomerID,
		arg.CustomerDisplayName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const saveAppointmentNotification = `-- name: SaveAppointmentNotification :exec
INSERT INTO appointment_notifications (
    correlation_key,
    agenda_event_id,
    notification_kind,
    notification_type,
    status,
    recipient_type,
    recipient_id,
    notification_idempotency_key,
    failure_reason,
    failure_message,
    created_at,
    completed_at,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (correlation_key) DO UPDATE SET
    agenda_event_id = $2,
    notification_kind = $3,
    notification_type = $4,
    status = $5,
    recipient_type = $6,
    recipient_id = $7,
    notification_idempotency_key = $8,
    failure_reason = $9,
    failure_message = $10,
    completed_at = $12,
    expires_at = $13
`

type SaveAppointmentNotificationParams struct {
	CorrelationKey             string             `json:"correlation_key"`
	AgendaEventID              string             `json:"agenda_event_id"`
	NotificationKind           string             `json:"notification_kind"`
	NotificationType           string             `json:"notification_type"`
	Status                     string             `json:"status"`
	RecipientType              string             `json:"recipient_type"`
	RecipientID                string             `json:"recipient_id"`
	NotificationIdempotencyKey pgtype.Text        `json:"notification_idempotency_key"`
	FailureReason              pgtype.Text        `json:"failure_reason"`
	FailureMessage             pgtype.Text        `json:"failure_message"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	CompletedAt                pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt                  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) SaveAppointmentNotification(ctx context.Context, arg SaveAppointmentNotificationParams) error {
	_, err := q.db.Exec(ctx, saveAppointmentNotification,
		arg.CorrelationKey,
		arg.AgendaEventID,
		arg.NotificationKind,
		arg.NotificationType,
		arg.Status,
		arg.RecipientType,
		arg.RecipientID,
		arg.NotificationIdempotencyKey,
		arg.FailureReason,
		arg.FailureMessage,
		arg.CreatedAt,
		arg.CompletedAt,
		arg.ExpiresAt,
	)
	return err
}

const saveAppointmentReminder = `-- name: SaveAppointmentReminder :exec
INSERT INTO appointment_reminders (
    agenda_event_id,
    status,
    remind_before_seconds,
    scheduled_at,
    sent_requested_at,
    sent_at,
    failed_at,
    failure_reason,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (agenda_event_id) DO UPDATE SET
    status = $2,
    remind_before_seconds = $3,
    scheduled_at = $4,
    sent_requested_at = $5,
    sent_at = $6,
    failed_at = $7,
    failure_reason = $8,
    updated_at = $9
`

type SaveAppointmentReminderParams struct {
	AgendaEventID       string             `json:"agenda_event_id"`
	Status              string             `json:"status"`
	RemindBeforeSeconds int32              `json:"remind_before_seconds"`
	ScheduledAt         pgtype.Timestamptz `json:"scheduled_at"`
	SentRequestedAt     pgtype.Timestamptz `json:"sent_requested_at"`
	SentAt              pgtype.Timestamptz `json:"sent_at"`
	FailedAt            pgtype.Timestamptz `json:"failed_at"`
	FailureReason       pgtype.Text        `json:"failure_reason"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SaveAppointmentReminder(ctx context.Context, arg SaveAppointmentReminderParams) error {
	_, err := q.db.Exec(ctx, saveAppointmentReminder,
		arg.AgendaEventID,
		arg.Status,
		arg.RemindBeforeSeconds,
		arg.ScheduledAt,
		arg.SentRequestedAt,
		arg.SentAt,
		arg.FailedAt,
		arg.FailureReason,
		arg.UpdatedAt,
	)
	return err
}

const saveAppointmentServiceItem = `-- name: SaveAppointmentServiceItem :exec
INSERT INTO appointment_service_items (
    agenda_event_id,
    service_id,
    service_name,
    price,
    position
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (agenda_event_id, position) DO UPDATE SET
    service_id = $2,
    service_name = $3,
    price = $4
`

type SaveAppointmentServiceItemParams struct {
	AgendaEventID string        `json:"agenda_event_id"`
	ServiceID     pgtype.Text   `json:"service_id"`
	ServiceName   string        `json:"service_name"`
	Price         pgtype.Float8 `json:"price"`
	Position      int32         `json:"position"`
}

func (q *Queries) SaveAppointmentServiceItem(ctx context.Context, arg SaveAppointmentServiceItemParams) error {
	_, err := q.db.Exec(ctx, saveAppointmentServiceItem,
		arg.AgendaEventID,
		arg.ServiceID,
		arg.ServiceName,
		arg.Price,
		arg.Position,
	)
	return err
}

const searchAgendaEventIDsFromDetails = `-- name: SearchAgendaEventIDsFromDetails :many
SELECT e.id
FROM agenda_events e
LEFT JOIN appointments a ON a.agenda_event_id = e.id
WHERE e.canceled_at IS NULL
  AND ($1::boolean = false OR e.calendar_id::text = $2::text)
  AND ($3::boolean = false OR a.customer_id::text = $4::text)
  AND ($5::boolean = false OR e.event_type = ANY($6::text[]))
  AND ($7::boolean = false OR (e.start_at < $8::timestamptz AND e.end_at > $9::timestamptz))
ORDER BY e.start_at ASC, e.end_at ASC
`

type SearchAgendaEventIDsFromDetailsParams struct {
	FilterCalendar   bool               `json:"filter_calendar"`
	CalendarID       string             `json:"calendar_id"`
	FilterCustomer   bool               `json:"filter_customer"`
	CustomerID       string             `json:"customer_id"`
	FilterEventTypes bool               `json:"filter_event_types"`
	EventTypes       []string           `json:"event_types"`
	FilterTimeRange  bool               `json:"filter_time_range"`
	EndAt            pgtype.Timestamptz `json:"end_at"`
	StartAt          pgtype.Timestamptz `json:"start_at"`
}

func (q *Queries) SearchAgendaEventIDsFromDetails(ctx context.Context, arg SearchAgendaEventIDsFromDetailsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, searchAgendaEventIDsFromDetails,
		arg.FilterCalendar,
		arg.CalendarID,
		arg.FilterCustomer,
		arg.CustomerID,
		arg.FilterEventTypes,
		arg.EventTypes,
		arg.FilterTimeRange,
		arg.EndAt,
		arg.StartAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
