// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointment_services.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAppointmentService = `-- name: FindAppointmentService :one
SELECT id, name, price, tags, color_hex
FROM appointment_services
WHERE id = $1
`

type FindAppointmentServiceRow struct {
	ID       string          `json:"id"`
	Name     string          `json:"name"`
	Price    float64         `json:"price"`
	Tags     json.RawMessage `json:"tags"`
	ColorHex pgtype.Text     `json:"color_hex"`
}

func (q *Queries) FindAppointmentService(ctx context.Context, id string) (FindAppointmentServiceRow, error) {
	row := q.db.QueryRow(ctx, findAppointmentService, id)
	var i FindAppointmentServiceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Tags,
		&i.ColorHex,
	)
	return i, err
}

const findAppointmentServices = `-- name: FindAppointmentServices :many
SELECT id, name, price, tags, color_hex
FROM appointment_services
ORDER BY name
`

type FindAppointmentServicesRow struct {
	ID       string          `json:"id"`
	Name     string          `json:"name"`
	Price    float64         `json:"price"`
	Tags     json.RawMessage `json:"tags"`
	ColorHex pgtype.Text     `json:"color_hex"`
}

func (q *Queries) FindAppointmentServices(ctx context.Context) ([]FindAppointmentServicesRow, error) {
	rows, err := q.db.Query(ctx, findAppointmentServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAppointmentServicesRow
	for rows.Next() {
		var i FindAppointmentServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Tags,
			&i.ColorHex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAppointmentService = `-- name: SaveAppointmentService :exec
INSERT INTO appointment_services (id, name, price, tags, color_hex)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    name = $2,
    price = $3,
    tags = $4,
    color_hex = $5
`

type SaveAppointmentServiceParams struct {
	ID       string          `json:"id"`
	Name     string          `json:"name"`
	Price    float64         `json:"price"`
	Tags     json.RawMessage `json:"tags"`
	ColorHex pgtype.Text     `json:"color_hex"`
}

func (q *Queries) SaveAppointmentService(ctx context.Context, arg SaveAppointmentServiceParams) error {
	_, err := q.db.Exec(ctx, saveAppointmentService,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Tags,
		arg.ColorHex,
	)
	return err
}

const searchAppointmentServices = `-- name: SearchAppointmentServices :many
SELECT id, name, price, tags, color_hex
FROM appointment_services
WHERE search_text ILIKE '%' || $1::text || '%'
   OR search_text % $1::text
ORDER BY similarity(search_text, $1::text) DESC, name
LIMIT $2::int
`

type SearchAppointmentServicesParams struct {
	Query      string `json:"query"`
	LimitCount int32  `json:"limit_count"`
}

type SearchAppointmentServicesRow struct {
	ID       string          `json:"id"`
	Name     string          `json:"name"`
	Price    float64         `json:"price"`
	Tags     json.RawMessage `json:"tags"`
	ColorHex pgtype.Text     `json:"color_hex"`
}

func (q *Queries) SearchAppointmentServices(ctx context.Context, arg SearchAppointmentServicesParams) ([]SearchAppointmentServicesRow, error) {
	rows, err := q.db.Query(ctx, searchAppointmentServices, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAppointmentServicesRow
	for rows.Next() {
		var i SearchAppointmentServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Tags,
			&i.ColorHex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
