// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type AgendaEvent struct {
	ID                  string             `json:"id"`
	EventType           string             `json:"event_type"`
	Title               string             `json:"title"`
	Description         string             `json:"description"`
	StartAt             pgtype.Timestamptz `json:"start_at"`
	EndAt               pgtype.Timestamptz `json:"end_at"`
	AttendeeID          string             `json:"attendee_id"`
	AttendeeDisplayName string             `json:"attendee_display_name"`
	Services            json.RawMessage    `json:"services"`
	CancelReason        pgtype.Text        `json:"cancel_reason"`
	ReminderStatus      string             `json:"reminder_status"`
	ReminderSentAt      pgtype.Timestamptz `json:"reminder_sent_at"`
	RemindBeforeSeconds int32              `json:"remind_before_seconds"`
	Version             int64              `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type AppointmentService struct {
	ID         string          `json:"id"`
	Name       string          `json:"name"`
	Price      float64         `json:"price"`
	Tags       json.RawMessage `json:"tags"`
	ColorHex   pgtype.Text     `json:"color_hex"`
	SearchText pgtype.Text     `json:"search_text"`
}

type PendingNotification struct {
	CorrelationKey   string             `json:"correlation_key"`
	AgendaEventID    string             `json:"agenda_event_id"`
	NotificationType string             `json:"notification_type"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}
