// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type AgendaEvent struct {
	ID                  string             `json:"id"`
	CalendarID          string             `json:"calendar_id"`
	EventType           string             `json:"event_type"`
	Title               string             `json:"title"`
	Description         string             `json:"description"`
	StartAt             pgtype.Timestamptz `json:"start_at"`
	EndAt               pgtype.Timestamptz `json:"end_at"`
	Timezone            string             `json:"timezone"`
	AllDay              bool               `json:"all_day"`
	DisplayTitle        pgtype.Text        `json:"display_title"`
	DisplayDescription  pgtype.Text        `json:"display_description"`
	Visibility          string             `json:"visibility"`
	AttendeeID          string             `json:"attendee_id"`
	AttendeeDisplayName string             `json:"attendee_display_name"`
	Services            json.RawMessage    `json:"services"`
	CancelReason        pgtype.Text        `json:"cancel_reason"`
	CanceledAt          pgtype.Timestamptz `json:"canceled_at"`
	ReminderStatus      string             `json:"reminder_status"`
	ReminderSentAt      pgtype.Timestamptz `json:"reminder_sent_at"`
	RemindBeforeSeconds int32              `json:"remind_before_seconds"`
	Version             int64              `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type AgendaManualEvent struct {
	AgendaEventID string             `json:"agenda_event_id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Location      pgtype.Text        `json:"location"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AgendaTimeBlock struct {
	AgendaEventID string             `json:"agenda_event_id"`
	Reason        string             `json:"reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Appointment struct {
	AgendaEventID       string             `json:"agenda_event_id"`
	CustomerID          string             `json:"customer_id"`
	CustomerDisplayName string             `json:"customer_display_name"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type AppointmentNotification struct {
	CorrelationKey             string             `json:"correlation_key"`
	AgendaEventID              string             `json:"agenda_event_id"`
	NotificationKind           string             `json:"notification_kind"`
	NotificationType           string             `json:"notification_type"`
	Status                     string             `json:"status"`
	RecipientType              string             `json:"recipient_type"`
	RecipientID                string             `json:"recipient_id"`
	NotificationIdempotencyKey pgtype.Text        `json:"notification_idempotency_key"`
	FailureReason              pgtype.Text        `json:"failure_reason"`
	FailureMessage             pgtype.Text        `json:"failure_message"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	CompletedAt                pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt                  pgtype.Timestamptz `json:"expires_at"`
}

type AppointmentReminder struct {
	AgendaEventID       string             `json:"agenda_event_id"`
	Status              string             `json:"status"`
	RemindBeforeSeconds int32              `json:"remind_before_seconds"`
	ScheduledAt         pgtype.Timestamptz `json:"scheduled_at"`
	SentRequestedAt     pgtype.Timestamptz `json:"sent_requested_at"`
	SentAt              pgtype.Timestamptz `json:"sent_at"`
	FailedAt            pgtype.Timestamptz `json:"failed_at"`
	FailureReason       pgtype.Text        `json:"failure_reason"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type AppointmentService struct {
	ID         string          `json:"id"`
	Name       string          `json:"name"`
	Tags       json.RawMessage `json:"tags"`
	ColorHex   pgtype.Text     `json:"color_hex"`
	SearchText pgtype.Text     `json:"search_text"`
}

type AppointmentServiceItem struct {
	AgendaEventID string      `json:"agenda_event_id"`
	ServiceID     pgtype.Text `json:"service_id"`
	ServiceName   string      `json:"service_name"`
	Position      int32       `json:"position"`
}

type PendingNotification struct {
	CorrelationKey   string             `json:"correlation_key"`
	AgendaEventID    string             `json:"agenda_event_id"`
	NotificationType string             `json:"notification_type"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}
