environment: dev
namespace: beaesthetic-dev
replicaCount: 1

image:
  tag: ""
  pullPolicy: Always

envConfig:
  APP__ENV: dev
  MONGO__DATABASE: notifications-v2-dev

resources:
  requests:
    memory: 100Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 100m

sidecar:
  outbox:
    configMapRefs:
      - notification-service-v2-config

volumes:
  - name: outbox-config
    configMap:
      name: notification-service-v2-outbox-config

