// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EmailChannelType.
const (
	Email EmailChannelType = "email"
)

// Valid indicates whether the value is a known member of the EmailChannelType enum.
func (e EmailChannelType) Valid() bool {
	switch e {
	case Email:
		return true
	default:
		return false
	}
}

// Defines values for SmsChannelType.
const (
	Sms SmsChannelType = "sms"
)

// Valid indicates whether the value is a known member of the SmsChannelType enum.
func (e SmsChannelType) Valid() bool {
	switch e {
	case Sms:
		return true
	default:
		return false
	}
}

// Defines values for WhatsappChannelType.
const (
	Whatsapp WhatsappChannelType = "whatsapp"
)

// Valid indicates whether the value is a known member of the WhatsappChannelType enum.
func (e WhatsappChannelType) Valid() bool {
	switch e {
	case Whatsapp:
		return true
	default:
		return false
	}
}

// EmailChannel defines model for EmailChannel.
type EmailChannel struct {
	Email string           `json:"email"`
	Type  EmailChannelType `json:"type"`
}

// EmailChannelType defines model for EmailChannel.Type.
type EmailChannelType string

// Notification defines model for Notification.
type Notification struct {
	Channel         *NotificationChannel `json:"channel,omitempty"`
	Content         *string              `json:"content,omitempty"`
	IsSent          *bool                `json:"isSent,omitempty"`
	IsSentConfirmed *bool                `json:"isSentConfirmed,omitempty"`
	NotificationId  *NotificationId      `json:"notificationId,omitempty"`
	Title           *string              `json:"title,omitempty"`
}

// NotificationChannel defines model for NotificationChannel.
type NotificationChannel struct {
	union json.RawMessage
}

// NotificationId defines model for NotificationId.
type NotificationId = openapi_types.UUID

// SendNotificationRequest defines model for SendNotificationRequest.
type SendNotificationRequest struct {
	Channel NotificationChannel `json:"channel"`
	Content string              `json:"content"`
	Title   string              `json:"title"`
}

// SmsChannel defines model for SmsChannel.
type SmsChannel struct {
	Phone string         `json:"phone"`
	Type  SmsChannelType `json:"type"`
}

// SmsChannelType defines model for SmsChannel.Type.
type SmsChannelType string

// WhatsappChannel defines model for WhatsappChannel.
type WhatsappChannel struct {
	Phone string              `json:"phone"`
	Type  WhatsappChannelType `json:"type"`
}

// WhatsappChannelType defines model for WhatsappChannel.Type.
type WhatsappChannelType string

// CreateNotificationJSONRequestBody defines body for CreateNotification for application/json ContentType.
type CreateNotificationJSONRequestBody = SendNotificationRequest

// AsSmsChannel returns the union data inside the NotificationChannel as a SmsChannel
func (t NotificationChannel) AsSmsChannel() (SmsChannel, error) {
	var body SmsChannel
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSmsChannel overwrites any union data inside the NotificationChannel as the provided SmsChannel
func (t *NotificationChannel) FromSmsChannel(v SmsChannel) error {
	v.Type = "sms"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSmsChannel performs a merge with any union data inside the NotificationChannel, using the provided SmsChannel
func (t *NotificationChannel) MergeSmsChannel(v SmsChannel) error {
	v.Type = "sms"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmailChannel returns the union data inside the NotificationChannel as a EmailChannel
func (t NotificationChannel) AsEmailChannel() (EmailChannel, error) {
	var body EmailChannel
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmailChannel overwrites any union data inside the NotificationChannel as the provided EmailChannel
func (t *NotificationChannel) FromEmailChannel(v EmailChannel) error {
	v.Type = "email"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmailChannel performs a merge with any union data inside the NotificationChannel, using the provided EmailChannel
func (t *NotificationChannel) MergeEmailChannel(v EmailChannel) error {
	v.Type = "email"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWhatsappChannel returns the union data inside the NotificationChannel as a WhatsappChannel
func (t NotificationChannel) AsWhatsappChannel() (WhatsappChannel, error) {
	var body WhatsappChannel
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWhatsappChannel overwrites any union data inside the NotificationChannel as the provided WhatsappChannel
func (t *NotificationChannel) FromWhatsappChannel(v WhatsappChannel) error {
	v.Type = "whatsapp"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWhatsappChannel performs a merge with any union data inside the NotificationChannel, using the provided WhatsappChannel
func (t *NotificationChannel) MergeWhatsappChannel(v WhatsappChannel) error {
	v.Type = "whatsapp"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NotificationChannel) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t NotificationChannel) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "email":
		return t.AsEmailChannel()
	case "sms":
		return t.AsSmsChannel()
	case "whatsapp":
		return t.AsWhatsappChannel()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t NotificationChannel) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NotificationChannel) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /notifications)
	CreateNotification(c *gin.Context)

	// (GET /notifications/{notificationId})
	GetNotification(c *gin.Context, notificationId NotificationId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateNotification operation middleware
func (siw *ServerInterfaceWrapper) CreateNotification(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateNotification(c)
}

// GetNotification operation middleware
func (siw *ServerInterfaceWrapper) GetNotification(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "notificationId" -------------
	var notificationId NotificationId

	err = runtime.BindStyledParameterWithOptions("simple", "notificationId", c.Param("notificationId"), &notificationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter notificationId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetNotification(c, notificationId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/notifications", wrapper.CreateNotification)
	router.GET(options.BaseURL+"/notifications/:notificationId", wrapper.GetNotification)
}

type CreateNotificationRequestObject struct {
	Body *CreateNotificationJSONRequestBody
}

type CreateNotificationResponseObject interface {
	VisitCreateNotificationResponse(w http.ResponseWriter) error
}

type CreateNotification200JSONResponse struct {
	NotificationId *NotificationId `json:"notificationId,omitempty"`
}

func (response CreateNotification200JSONResponse) VisitCreateNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateNotification400Response struct {
}

func (response CreateNotification400Response) VisitCreateNotificationResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetNotificationRequestObject struct {
	NotificationId NotificationId `json:"notificationId"`
}

type GetNotificationResponseObject interface {
	VisitGetNotificationResponse(w http.ResponseWriter) error
}

type GetNotification200JSONResponse Notification

func (response GetNotification200JSONResponse) VisitGetNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNotification400Response struct {
}

func (response GetNotification400Response) VisitGetNotificationResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetNotification404Response struct {
}

func (response GetNotification404Response) VisitGetNotificationResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /notifications)
	CreateNotification(ctx context.Context, request CreateNotificationRequestObject) (CreateNotificationResponseObject, error)

	// (GET /notifications/{notificationId})
	GetNotification(ctx context.Context, request GetNotificationRequestObject) (GetNotificationResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// CreateNotification operation middleware
func (sh *strictHandler) CreateNotification(ctx *gin.Context) {
	var request CreateNotificationRequestObject

	var body CreateNotificationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateNotification(ctx, request.(CreateNotificationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateNotification")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateNotificationResponseObject); ok {
		if err := validResponse.VisitCreateNotificationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNotification operation middleware
func (sh *strictHandler) GetNotification(ctx *gin.Context, notificationId NotificationId) {
	var request GetNotificationRequestObject

	request.NotificationId = notificationId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetNotification(ctx, request.(GetNotificationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNotification")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetNotificationResponseObject); ok {
		if err := validResponse.VisitGetNotificationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
