openapi: 3.0.0
info:
  title: Fidelity Card API
  description: |
    Welcome to the Customer API documentation. This API allows you to manage customer data, including creating, updating, searching, and retrieving customer records. It provides endpoints for various customer-related operations.
    
    ## Endpoints
    - **Get Customers**: Retrieve a list of customers with pagination support.
    - **Search Customers**: Search for customers by name or other criteria.
    - **Get Customer by ID**: Retrieve a customer's details by their unique ID.
    - **Create Customer**: Create a new customer record.
    - **Update Customer**: Update an existing customer's information.
    
    ## Request and Response Formats
    All requests and responses follow the JSON format. Please refer to the schemas section for detailed information on request and response payloads.
    
    ## Error Handling
    In case of errors, the API will respond with appropriate status codes and error messages. Refer to the error handling section for a list of possible errors and their meanings.
    
    ## Version
    This documentation covers version 1.0.0 of the Customer API.
  contact:
    email: petretiandrea@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://agenda.beaesthetic.it/customer-service/
paths:
  /fidelity-cards/:
    post:
      tags:
        - fidelity-cards
      operationId: createFidelityCard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  $ref: "#/components/schemas/CustomerId"
              required:
                - customerId
      responses:
        '200':
          description: 'Created'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FidelityCardResponse"
        '400':
          description: Bad request
    get:
      tags:
        - fidelity-cards
      operationId: getFidelityCards
      responses:
        '200':
          description: 'Fidelity card'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FidelityCardResponse"
        '400':
          description: Bad request

  /fidelity-cards/{cardId}:
    get:
      tags:
        - fidelity-cards
      operationId: getFidelityCardById
      parameters:
        - in: path
          name: cardId
          required: true
          description: Card Id
          schema:
            $ref: "#/components/schemas/FidelityCardId"
      responses:
        '200':
          description: 'Fidelity card'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FidelityCardResponse"
        '400':
          description: Bad request
        '404':
          description: Not found

  /fidelity-cards/customers/{customerId}:
    get:
      tags:
        - fidelity-cards
      operationId: getFidelityCardsByCustomerId
      parameters:
        - in: path
          name: customerId
          required: true
          description: Customer Id
          schema:
            $ref: "#/components/schemas/CustomerId"
      responses:
        '200':
          description: 'Fidelity card'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FidelityCardResponse"
        '400':
          description: Bad request

  /fidelity-cards/{cardId}/purchase:
    put:
      tags:
        - fidelity-cards
      operationId: notifyPurchase
      parameters:
        - in: path
          name: cardId
          required: true
          description: Card Id
          schema:
            $ref: "#/components/schemas/FidelityCardId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PurchaseNofityRequest"
      responses:
        '201':
          description: 'Purchase created'

  /fidelity-cards/vouchers/{voucherId}:
    delete:
      tags:
        - fidelity-cards
      operationId: useVoucher
      parameters:
        - in: path
          name: voucherId
          required: true
          description: "The voucher id"
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: "The updated fidelity card after voucher usage"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FidelityCardResponse"

components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        surname:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
      required: [id, name, surname]
    FidelityCardId:
      type: string
      format: uuid
    CustomerId:
      type: string
      format: uuid
    FidelityCardResponse:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/FidelityCardId"
        customer:
          $ref: "#/components/schemas/Customer"
        solariumPurchases:
          type: integer
        vouchers:
          type: array
          items:
            $ref: "#/components/schemas/Voucher"
    Voucher:
      oneOf:
        - $ref: "#/components/schemas/FreeVoucher"
        - $ref: "#/components/schemas/DiscountVoucher"
        - $ref: "#/components/schemas/TreatmentDiscountVoucher"
      discriminator:
        propertyName: type
        mapping:
          free: "#/components/schemas/FreeVoucher"
          discount: "#/components/schemas/DiscountVoucher"
          treatmentDiscount: "#/components/schemas/TreatmentDiscountVoucher"

    FreeVoucher:
      x-implements: "it.beaesthetic.fidelity.rest.serialization.VoucherItemMixin"
      type: object
      properties:
        id:
          $ref: "#/components/schemas/FidelityCardId"
        issuedAt:
          type: string
          format: date-time
        isUsed:
          type: boolean
        treatment:
          $ref: "#/components/schemas/SupportedVoucherTreatment"
    DiscountVoucher:
      x-implements: "it.beaesthetic.fidelity.rest.serialization.VoucherItemMixin"
      type: object
      properties:
        id:
          $ref: "#/components/schemas/FidelityCardId"
        issuedAt:
          type: string
          format: date-time
        isUsed:
          type: boolean
        amount:
          type: number
    TreatmentDiscountVoucher:
      x-implements: "it.beaesthetic.fidelity.rest.serialization.VoucherItemMixin"
      type: object
      properties:
        id:
          $ref: "#/components/schemas/FidelityCardId"
        issuedAt:
          type: string
          format: date-time
        isUsed:
          type: boolean
        treatment:
          $ref: "#/components/schemas/SupportedVoucherTreatment"
        amount:
          type: number

    SupportedVoucherTreatment:
      type: string
      enum:
        - SOLARIUM

    PurchaseNofityRequest:
      type: object
      properties:
        amount:
          type: number
        treatment:
          $ref: '#/components/schemas/SupportedVoucherTreatment'
      required:
        - amount