openapi: 3.0.0
info:
  title: Customer Wallet API
  description: |
    Welcome to the Customer API documentation. This API allows you to manage customer data, including creating, updating, searching, and retrieving customer records. It provides endpoints for various customer-related operations.
    
    ## Endpoints
    - **Get Customers**: Retrieve a list of customers with pagination support.
    - **Search Customers**: Search for customers by name or other criteria.
    - **Get Customer by ID**: Retrieve a customer's details by their unique ID.
    - **Create Customer**: Create a new customer record.
    - **Update Customer**: Update an existing customer's information.
    
    ## Request and Response Formats
    All requests and responses follow the JSON format. Please refer to the schemas section for detailed information on request and response payloads.
    
    ## Error Handling
    In case of errors, the API will respond with appropriate status codes and error messages. Refer to the error handling section for a list of possible errors and their meanings.
    
    ## Version
    This documentation covers version 1.0.0 of the Customer API.
  contact:
    email: petretiandrea@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://agenda.beaesthetic.it/customer-service/
paths:

  /admin/wallets/giftCard:
    post:
      tags:
        - wallets-admin
      operationId: addGiftCard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                customerId:
                  $ref: '#/components/schemas/CustomerId'
              required:
                - amount
                - customerId
      responses:
        '200':
          description: "Wallet id where gift card has been added"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: '#/components/schemas/WalletId'
        '400':
          description: "Bad request"

  /admin/wallets/{walletId}/charge:
    put:
      tags:
        - wallets-admin
      operationId: chargeWallet
      parameters:
        - in: path
          name: walletId
          required: true
          schema:
            $ref: '#/components/schemas/WalletId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
              required:
                - amount
      responses:
        '200':
          description: "Charge wallet successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: '#/components/schemas/WalletId'

  /admin/wallets/{walletId}:
    get:
      tags:
        - wallets-admin
      operationId: getWalletById
      parameters:
        - in: path
          name: walletId
          required: true
          schema:
            $ref: '#/components/schemas/WalletId'
      responses:
        '200':
          description: Wallet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
        '400':
          description: Bad request
        '404':
          description: Not found

  /admin/wallets:
    get:
      tags:
        - wallets-admin
      operationId: getWallets
      parameters:
        - in: query
          name: filter
          schema:
            type: string
            default: null
      responses:
        '200':
          description: All matching wallets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Wallet'
        '400':
          description: Bad request

components:
  schemas:
    Wallet:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/WalletId'
        customer:
          $ref: '#/components/schemas/Customer'
        availableAmount:
          type: number
        spent:
          type: number
        history:
          type: array
          items:
            $ref: '#/components/schemas/WalletOperation'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Customer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        surname:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
      required: [id, name, surname]

    WalletId:
      type: string
      format: uuid
    GiftCardId:
      type: string
      format: uuid
    CustomerId:
      type: string
      format: uuid

    WalletOperation:
      oneOf:
        - $ref: '#/components/schemas/MoneyCreditedEvent'
        - $ref: '#/components/schemas/MoneyChargedEvent'
        - $ref: '#/components/schemas/GiftCardMoneyCreditedEvent'
        - $ref: '#/components/schemas/GiftCardMoneyExpiredEvent'

    MoneyCreditedEvent:
      x-implements: it.beaesthetic.wallet.http.serialization.WalletEventDtoMixin
      type: object
      properties:
        amount:
          type: number
        at:
          type: string
          format: date-time

    GiftCardMoneyCreditedEvent:
      x-implements: it.beaesthetic.wallet.http.serialization.WalletEventDtoMixin
      type: object
      properties:
        giftCardId:
          $ref: '#/components/schemas/GiftCardId'
        amount:
          type: number
        at:
          type: string
          format: date-time
        expireAt:
          type: string
          format: date-time

    GiftCardMoneyExpiredEvent:
      x-implements: it.beaesthetic.wallet.http.serialization.WalletEventDtoMixin
      type: object
      properties:
        giftCardId:
          $ref: '#/components/schemas/GiftCardId'
        at:
          type: string
          format: date-time
        amount:
          type: number

    MoneyChargedEvent:
      x-implements: it.beaesthetic.wallet.http.serialization.WalletEventDtoMixin
      type: object
      properties:
        amount:
          type: number
        at:
          type: string
          format: date-time