// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const archiveDeletedCustomer = `-- name: ArchiveDeletedCustomer :execrows
INSERT INTO deleted_customers (id, name, surname, email, phone, note)
SELECT c.id, c.name, c.surname, c.email, c.phone, c.note
FROM customers c
WHERE c.id = $1
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) ArchiveDeletedCustomer(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveDeletedCustomer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers
WHERE id = $1
`

func (q *Queries) DeleteCustomer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomer, id)
	return err
}

const findCustomerByID = `-- name: FindCustomerByID :one
SELECT id, name, surname, email, phone, note
FROM customers
WHERE id = $1
`

type FindCustomerByIDRow struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	Surname string         `json:"surname"`
	Email   sql.NullString `json:"email"`
	Phone   sql.NullString `json:"phone"`
	Note    string         `json:"note"`
}

func (q *Queries) FindCustomerByID(ctx context.Context, id string) (FindCustomerByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findCustomerByID, id)
	var i FindCustomerByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Phone,
		&i.Note,
	)
	return i, err
}

const findCustomerByPhone = `-- name: FindCustomerByPhone :one
SELECT id, name, surname, email, phone, note
FROM customers
WHERE phone = $1
LIMIT 1
`

type FindCustomerByPhoneRow struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	Surname string         `json:"surname"`
	Email   sql.NullString `json:"email"`
	Phone   sql.NullString `json:"phone"`
	Note    string         `json:"note"`
}

func (q *Queries) FindCustomerByPhone(ctx context.Context, phone sql.NullString) (FindCustomerByPhoneRow, error) {
	row := q.db.QueryRowContext(ctx, findCustomerByPhone, phone)
	var i FindCustomerByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Phone,
		&i.Note,
	)
	return i, err
}

const findCustomers = `-- name: FindCustomers :many
SELECT id, name, surname, email, phone, note
FROM customers
ORDER BY name, surname
LIMIT $1
`

type FindCustomersRow struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	Surname string         `json:"surname"`
	Email   sql.NullString `json:"email"`
	Phone   sql.NullString `json:"phone"`
	Note    string         `json:"note"`
}

func (q *Queries) FindCustomers(ctx context.Context, limit int32) ([]FindCustomersRow, error) {
	rows, err := q.db.QueryContext(ctx, findCustomers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCustomersRow
	for rows.Next() {
		var i FindCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Email,
			&i.Phone,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCustomersPageByNameAsc = `-- name: FindCustomersPageByNameAsc :many
SELECT id, name, surname, email, phone, note
FROM customers
ORDER BY name ASC, id
LIMIT $1 OFFSET $2
`

type FindCustomersPageByNameAscParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type FindCustomersPageByNameAscRow struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	Surname string         `json:"surname"`
	Email   sql.NullString `json:"email"`
	Phone   sql.NullString `json:"phone"`
	Note    string         `json:"note"`
}

func (q *Queries) FindCustomersPageByNameAsc(ctx context.Context, arg FindCustomersPageByNameAscParams) ([]FindCustomersPageByNameAscRow, error) {
	rows, err := q.db.QueryContext(ctx, findCustomersPageByNameAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCustomersPageByNameAscRow
	for rows.Next() {
		var i FindCustomersPageByNameAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Email,
			&i.Phone,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCustomersPageByNameDesc = `-- name: FindCustomersPageByNameDesc :many
SELECT id, name, surname, email, phone, note
FROM customers
ORDER BY name DESC, id
LIMIT $1 OFFSET $2
`

type FindCustomersPageByNameDescParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type FindCustomersPageByNameDescRow struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	Surname string         `json:"surname"`
	Email   sql.NullString `json:"email"`
	Phone   sql.NullString `json:"phone"`
	Note    string         `json:"note"`
}

func (q *Queries) FindCustomersPageByNameDesc(ctx context.Context, arg FindCustomersPageByNameDescParams) ([]FindCustomersPageByNameDescRow, error) {
	rows, err := q.db.QueryContext(ctx, findCustomersPageByNameDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCustomersPageByNameDescRow
	for rows.Next() {
		var i FindCustomersPageByNameDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Email,
			&i.Phone,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCustomersPageBySurnameAsc = `-- name: FindCustomersPageBySurnameAsc :many
SELECT id, name, surname, email, phone, note
FROM customers
ORDER BY surname ASC, id
LIMIT $1 OFFSET $2
`

type FindCustomersPageBySurnameAscParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type FindCustomersPageBySurnameAscRow struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	Surname string         `json:"surname"`
	Email   sql.NullString `json:"email"`
	Phone   sql.NullString `json:"phone"`
	Note    string         `json:"note"`
}

func (q *Queries) FindCustomersPageBySurnameAsc(ctx context.Context, arg FindCustomersPageBySurnameAscParams) ([]FindCustomersPageBySurnameAscRow, error) {
	rows, err := q.db.QueryContext(ctx, findCustomersPageBySurnameAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCustomersPageBySurnameAscRow
	for rows.Next() {
		var i FindCustomersPageBySurnameAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Email,
			&i.Phone,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCustomersPageBySurnameDesc = `-- name: FindCustomersPageBySurnameDesc :many
SELECT id, name, surname, email, phone, note
FROM customers
ORDER BY surname DESC, id
LIMIT $1 OFFSET $2
`

type FindCustomersPageBySurnameDescParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type FindCustomersPageBySurnameDescRow struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	Surname string         `json:"surname"`
	Email   sql.NullString `json:"email"`
	Phone   sql.NullString `json:"phone"`
	Note    string         `json:"note"`
}

func (q *Queries) FindCustomersPageBySurnameDesc(ctx context.Context, arg FindCustomersPageBySurnameDescParams) ([]FindCustomersPageBySurnameDescRow, error) {
	rows, err := q.db.QueryContext(ctx, findCustomersPageBySurnameDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCustomersPageBySurnameDescRow
	for rows.Next() {
		var i FindCustomersPageBySurnameDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Email,
			&i.Phone,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCustomersPageByUpdatedAtAsc = `-- name: FindCustomersPageByUpdatedAtAsc :many
SELECT id, name, surname, email, phone, note
FROM customers
ORDER BY updated_at ASC, id
LIMIT $1 OFFSET $2
`

type FindCustomersPageByUpdatedAtAscParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type FindCustomersPageByUpdatedAtAscRow struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	Surname string         `json:"surname"`
	Email   sql.NullString `json:"email"`
	Phone   sql.NullString `json:"phone"`
	Note    string         `json:"note"`
}

func (q *Queries) FindCustomersPageByUpdatedAtAsc(ctx context.Context, arg FindCustomersPageByUpdatedAtAscParams) ([]FindCustomersPageByUpdatedAtAscRow, error) {
	rows, err := q.db.QueryContext(ctx, findCustomersPageByUpdatedAtAsc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCustomersPageByUpdatedAtAscRow
	for rows.Next() {
		var i FindCustomersPageByUpdatedAtAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Email,
			&i.Phone,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCustomersPageByUpdatedAtDesc = `-- name: FindCustomersPageByUpdatedAtDesc :many
SELECT id, name, surname, email, phone, note
FROM customers
ORDER BY updated_at DESC, id
LIMIT $1 OFFSET $2
`

type FindCustomersPageByUpdatedAtDescParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type FindCustomersPageByUpdatedAtDescRow struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	Surname string         `json:"surname"`
	Email   sql.NullString `json:"email"`
	Phone   sql.NullString `json:"phone"`
	Note    string         `json:"note"`
}

func (q *Queries) FindCustomersPageByUpdatedAtDesc(ctx context.Context, arg FindCustomersPageByUpdatedAtDescParams) ([]FindCustomersPageByUpdatedAtDescRow, error) {
	rows, err := q.db.QueryContext(ctx, findCustomersPageByUpdatedAtDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindCustomersPageByUpdatedAtDescRow
	for rows.Next() {
		var i FindCustomersPageByUpdatedAtDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Email,
			&i.Phone,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCustomer = `-- name: SaveCustomer :exec
INSERT INTO customers (id, name, surname, email, phone, note, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    name = $2,
    surname = $3,
    email = $4,
    phone = $5,
    note = $6,
    updated_at = $7
`

type SaveCustomerParams struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Surname   string         `json:"surname"`
	Email     sql.NullString `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Note      string         `json:"note"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) SaveCustomer(ctx context.Context, arg SaveCustomerParams) error {
	_, err := q.db.ExecContext(ctx, saveCustomer,
		arg.ID,
		arg.Name,
		arg.Surname,
		arg.Email,
		arg.Phone,
		arg.Note,
		arg.UpdatedAt,
	)
	return err
}

const searchCustomers = `-- name: SearchCustomers :many
SELECT id, name, surname, email, phone, note
FROM customers
WHERE search_text ILIKE '%' || $1 || '%' OR search_text % $1
ORDER BY similarity(search_text, $1) DESC, name, surname
LIMIT $2
`

type SearchCustomersParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
}

type SearchCustomersRow struct {
	ID      string         `json:"id"`
	Name    string         `json:"name"`
	Surname string         `json:"surname"`
	Email   sql.NullString `json:"email"`
	Phone   sql.NullString `json:"phone"`
	Note    string         `json:"note"`
}

func (q *Queries) SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]SearchCustomersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCustomers, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCustomersRow
	for rows.Next() {
		var i SearchCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Email,
			&i.Phone,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
