// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fidelity.sql

package queries

import (
	"context"
	"encoding/json"
)

const findFidelityCardByID = `-- name: FindFidelityCardByID :one
SELECT id, customer_id, solarium_purchases, vouchers
FROM fidelity_cards
WHERE id = $1
`

type FindFidelityCardByIDRow struct {
	ID                string          `json:"id"`
	CustomerID        string          `json:"customer_id"`
	SolariumPurchases int32           `json:"solarium_purchases"`
	Vouchers          json.RawMessage `json:"vouchers"`
}

func (q *Queries) FindFidelityCardByID(ctx context.Context, id string) (FindFidelityCardByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findFidelityCardByID, id)
	var i FindFidelityCardByIDRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.SolariumPurchases,
		&i.Vouchers,
	)
	return i, err
}

const findFidelityCardByVoucherID = `-- name: FindFidelityCardByVoucherID :one
SELECT id, customer_id, solarium_purchases, vouchers
FROM fidelity_cards
WHERE vouchers @> $1::jsonb
LIMIT 1
`

type FindFidelityCardByVoucherIDRow struct {
	ID                string          `json:"id"`
	CustomerID        string          `json:"customer_id"`
	SolariumPurchases int32           `json:"solarium_purchases"`
	Vouchers          json.RawMessage `json:"vouchers"`
}

func (q *Queries) FindFidelityCardByVoucherID(ctx context.Context, dollar_1 json.RawMessage) (FindFidelityCardByVoucherIDRow, error) {
	row := q.db.QueryRowContext(ctx, findFidelityCardByVoucherID, dollar_1)
	var i FindFidelityCardByVoucherIDRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.SolariumPurchases,
		&i.Vouchers,
	)
	return i, err
}

const findFidelityCards = `-- name: FindFidelityCards :many
SELECT id, customer_id, solarium_purchases, vouchers
FROM fidelity_cards
ORDER BY created_at DESC
`

type FindFidelityCardsRow struct {
	ID                string          `json:"id"`
	CustomerID        string          `json:"customer_id"`
	SolariumPurchases int32           `json:"solarium_purchases"`
	Vouchers          json.RawMessage `json:"vouchers"`
}

func (q *Queries) FindFidelityCards(ctx context.Context) ([]FindFidelityCardsRow, error) {
	rows, err := q.db.QueryContext(ctx, findFidelityCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindFidelityCardsRow
	for rows.Next() {
		var i FindFidelityCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.SolariumPurchases,
			&i.Vouchers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFidelityCardsByCustomerID = `-- name: FindFidelityCardsByCustomerID :many
SELECT id, customer_id, solarium_purchases, vouchers
FROM fidelity_cards
WHERE customer_id = $1
`

type FindFidelityCardsByCustomerIDRow struct {
	ID                string          `json:"id"`
	CustomerID        string          `json:"customer_id"`
	SolariumPurchases int32           `json:"solarium_purchases"`
	Vouchers          json.RawMessage `json:"vouchers"`
}

func (q *Queries) FindFidelityCardsByCustomerID(ctx context.Context, customerID string) ([]FindFidelityCardsByCustomerIDRow, error) {
	rows, err := q.db.QueryContext(ctx, findFidelityCardsByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindFidelityCardsByCustomerIDRow
	for rows.Next() {
		var i FindFidelityCardsByCustomerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.SolariumPurchases,
			&i.Vouchers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveFidelityCard = `-- name: SaveFidelityCard :exec
INSERT INTO fidelity_cards (id, customer_id, solarium_purchases, vouchers, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (id) DO UPDATE SET
    customer_id = $2,
    solarium_purchases = $3,
    vouchers = $4,
    updated_at = now()
`

type SaveFidelityCardParams struct {
	ID                string          `json:"id"`
	CustomerID        string          `json:"customer_id"`
	SolariumPurchases int32           `json:"solarium_purchases"`
	Vouchers          json.RawMessage `json:"vouchers"`
}

func (q *Queries) SaveFidelityCard(ctx context.Context, arg SaveFidelityCardParams) error {
	_, err := q.db.ExecContext(ctx, saveFidelityCard,
		arg.ID,
		arg.CustomerID,
		arg.SolariumPurchases,
		arg.Vouchers,
	)
	return err
}
