// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Customer struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Surname    string         `json:"surname"`
	Email      sql.NullString `json:"email"`
	Phone      sql.NullString `json:"phone"`
	Note       string         `json:"note"`
	SearchText sql.NullString `json:"search_text"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type DeletedCustomer struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Surname   string         `json:"surname"`
	Email     sql.NullString `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Note      string         `json:"note"`
	DeletedAt time.Time      `json:"deleted_at"`
}

type FidelityCard struct {
	ID                string          `json:"id"`
	CustomerID        string          `json:"customer_id"`
	SolariumPurchases int32           `json:"solarium_purchases"`
	Vouchers          json.RawMessage `json:"vouchers"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type Wallet struct {
	ID              string          `json:"id"`
	Owner           string          `json:"owner"`
	AvailableAmount float64         `json:"available_amount"`
	Spent           float64         `json:"spent"`
	Operations      json.RawMessage `json:"operations"`
	GiftCards       json.RawMessage `json:"gift_cards"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}
