// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const findWalletByCustomerID = `-- name: FindWalletByCustomerID :one
SELECT id, owner, available_amount, spent, operations, gift_cards, created_at, updated_at
FROM wallets
WHERE owner = $1
`

func (q *Queries) FindWalletByCustomerID(ctx context.Context, owner string) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, findWalletByCustomerID, owner)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.AvailableAmount,
		&i.Spent,
		&i.Operations,
		&i.GiftCards,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findWalletByID = `-- name: FindWalletByID :one
SELECT id, owner, available_amount, spent, operations, gift_cards, created_at, updated_at
FROM wallets
WHERE id = $1
`

func (q *Queries) FindWalletByID(ctx context.Context, id string) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, findWalletByID, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.AvailableAmount,
		&i.Spent,
		&i.Operations,
		&i.GiftCards,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findWalletReadModelByID = `-- name: FindWalletReadModelByID :one
SELECT
    w.id,
    w.owner,
    w.available_amount,
    w.spent,
    w.operations,
    w.gift_cards,
    w.created_at,
    w.updated_at,
    c.id AS customer_id,
    c.name,
    c.surname,
    c.email,
    c.phone,
    c.note
FROM wallets w
JOIN customers c ON c.id = w.owner
WHERE w.id = $1
`

type FindWalletReadModelByIDRow struct {
	ID              string          `json:"id"`
	Owner           string          `json:"owner"`
	AvailableAmount float64         `json:"available_amount"`
	Spent           float64         `json:"spent"`
	Operations      json.RawMessage `json:"operations"`
	GiftCards       json.RawMessage `json:"gift_cards"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	CustomerID      string          `json:"customer_id"`
	Name            string          `json:"name"`
	Surname         string          `json:"surname"`
	Email           sql.NullString  `json:"email"`
	Phone           sql.NullString  `json:"phone"`
	Note            string          `json:"note"`
}

func (q *Queries) FindWalletReadModelByID(ctx context.Context, id string) (FindWalletReadModelByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findWalletReadModelByID, id)
	var i FindWalletReadModelByIDRow
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.AvailableAmount,
		&i.Spent,
		&i.Operations,
		&i.GiftCards,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Phone,
		&i.Note,
	)
	return i, err
}

const findWalletReadModels = `-- name: FindWalletReadModels :many
SELECT
    w.id,
    w.owner,
    w.available_amount,
    w.spent,
    w.operations,
    w.gift_cards,
    w.created_at,
    w.updated_at,
    c.id AS customer_id,
    c.name,
    c.surname,
    c.email,
    c.phone,
    c.note
FROM wallets w
JOIN customers c ON c.id = w.owner
ORDER BY w.created_at DESC
`

type FindWalletReadModelsRow struct {
	ID              string          `json:"id"`
	Owner           string          `json:"owner"`
	AvailableAmount float64         `json:"available_amount"`
	Spent           float64         `json:"spent"`
	Operations      json.RawMessage `json:"operations"`
	GiftCards       json.RawMessage `json:"gift_cards"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	CustomerID      string          `json:"customer_id"`
	Name            string          `json:"name"`
	Surname         string          `json:"surname"`
	Email           sql.NullString  `json:"email"`
	Phone           sql.NullString  `json:"phone"`
	Note            string          `json:"note"`
}

func (q *Queries) FindWalletReadModels(ctx context.Context) ([]FindWalletReadModelsRow, error) {
	rows, err := q.db.QueryContext(ctx, findWalletReadModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindWalletReadModelsRow
	for rows.Next() {
		var i FindWalletReadModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.AvailableAmount,
			&i.Spent,
			&i.Operations,
			&i.GiftCards,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerID,
			&i.Name,
			&i.Surname,
			&i.Email,
			&i.Phone,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveWallet = `-- name: SaveWallet :exec
INSERT INTO wallets (id, owner, available_amount, spent, operations, gift_cards, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    owner = $2,
    available_amount = $3,
    spent = $4,
    operations = $5,
    gift_cards = $6,
    updated_at = $8
`

type SaveWalletParams struct {
	ID              string          `json:"id"`
	Owner           string          `json:"owner"`
	AvailableAmount float64         `json:"available_amount"`
	Spent           float64         `json:"spent"`
	Operations      json.RawMessage `json:"operations"`
	GiftCards       json.RawMessage `json:"gift_cards"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

func (q *Queries) SaveWallet(ctx context.Context, arg SaveWalletParams) error {
	_, err := q.db.ExecContext(ctx, saveWallet,
		arg.ID,
		arg.Owner,
		arg.AvailableAmount,
		arg.Spent,
		arg.Operations,
		arg.GiftCards,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const searchWalletReadModels = `-- name: SearchWalletReadModels :many
SELECT
    w.id,
    w.owner,
    w.available_amount,
    w.spent,
    w.operations,
    w.gift_cards,
    w.created_at,
    w.updated_at,
    c.id AS customer_id,
    c.name,
    c.surname,
    c.email,
    c.phone,
    c.note
FROM wallets w
JOIN customers c ON c.id = w.owner
WHERE c.search_text ILIKE '%' || $1 || '%' OR c.search_text % $1
ORDER BY w.created_at DESC
`

type SearchWalletReadModelsRow struct {
	ID              string          `json:"id"`
	Owner           string          `json:"owner"`
	AvailableAmount float64         `json:"available_amount"`
	Spent           float64         `json:"spent"`
	Operations      json.RawMessage `json:"operations"`
	GiftCards       json.RawMessage `json:"gift_cards"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	CustomerID      string          `json:"customer_id"`
	Name            string          `json:"name"`
	Surname         string          `json:"surname"`
	Email           sql.NullString  `json:"email"`
	Phone           sql.NullString  `json:"phone"`
	Note            string          `json:"note"`
}

func (q *Queries) SearchWalletReadModels(ctx context.Context, dollar_1 sql.NullString) ([]SearchWalletReadModelsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchWalletReadModels, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchWalletReadModelsRow
	for rows.Next() {
		var i SearchWalletReadModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.AvailableAmount,
			&i.Spent,
			&i.Operations,
			&i.GiftCards,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerID,
			&i.Name,
			&i.Surname,
			&i.Email,
			&i.Phone,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
