openapi: 3.0.0
info:
  title: Customer API
  description: |
    Welcome to the Customer API documentation. This API allows you to manage customer data, including creating, updating, searching, and retrieving customer records. It provides endpoints for various customer-related operations.
    
    ## Endpoints
    - **Get Customers**: Retrieve a list of customers with pagination support.
    - **Search Customers**: Search for customers by name or other criteria.
    - **Get Customer by ID**: Retrieve a customer's details by their unique ID.
    - **Create Customer**: Create a new customer record.
    - **Update Customer**: Update an existing customer's information.
    
    ## Request and Response Formats
    All requests and responses follow the JSON format. Please refer to the schemas section for detailed information on request and response payloads.
    
    ## Error Handling
    In case of errors, the API will respond with appropriate status codes and error messages. Refer to the error handling section for a list of possible errors and their meanings.
    
    ## Version
    This documentation covers version 1.0.0 of the Customer API.
  contact:
    email: petretiandrea@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://agenda.beaesthetic.it/customer-service/
paths:
  /customers/page/{direction}:
    get:
      summary: Get customers with pagination
      operationId: getCustomerByPage
      tags:
        - Customers
      parameters:
        - name: direction
          required: true
          in: path
          description: Pagination direction (optional)
          schema:
            type: string
            enum:
              - prev
              - next
        - name: pageToken
          in: query
          description: Page token (optional)
          schema:
            type: string
        - name: limit
          in: query
          description: Page size (optional)
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomersPaginated'
  /customers/search:
    get:
      summary: Search for customers
      operationId: searchCustomer
      tags:
        - Customers
      parameters:
        - name: limit
          in: query
          description: Maximum number of results (optional)
          schema:
            type: integer
        - name: filter
          in: query
          description: Text to filter by (required)
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerResponse'
  /customers:
    get:
      summary: Get all customers
      operationId: getAllCustomers
      tags:
        - Customers
      parameters:
        - name: limit
          in: query
          description: Maximum number of results (optional)
          schema:
            type: integer
        - name: filter
          in: query
          description: Text to filter by (optional)
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CustomerResponse'
    post:
      summary: Create a new customer
      operationId: createCustomer
      tags:
        - Customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerCreate'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
  /customers/{customerId}:
    get:
      operationId: getCustomerById
      summary: Get customer by ID
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          description: Customer ID
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
    put:
      summary: Update customer by ID
      operationId: updateCustomerById
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          description: Customer ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerUpdate'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'

components:
  schemas:
    CustomerResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        surname:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        note:
          type: string
      required:
        - id
        - name
        - surname

    CustomerCreate:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        note:
          type: string
      required:
        - name

    CustomerUpdate:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        note:
          type: string

    CustomersPaginated:
      type: object
      properties:
        itemCount:
          type: number
        items:
          type: array
          items:
            $ref: '#/components/schemas/CustomerResponse'
        nextCursor:
          type: string
        hasNextPage:
          type: boolean
        hasPreviousPage:
          type: boolean