// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_notifications.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingCustomerNotification = `-- name: CreatePendingCustomerNotification :execrows
INSERT INTO customer_notifications (
    id,
    idempotency_key,
    correlation_key,
    customer_id,
    notification_type,
    notification_channel,
    template_values,
    status,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (idempotency_key) DO NOTHING
`

type CreatePendingCustomerNotificationParams struct {
	ID                  string             `json:"id"`
	IdempotencyKey      string             `json:"idempotency_key"`
	CorrelationKey      string             `json:"correlation_key"`
	CustomerID          string             `json:"customer_id"`
	NotificationType    string             `json:"notification_type"`
	NotificationChannel string             `json:"notification_channel"`
	TemplateValues      json.RawMessage    `json:"template_values"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePendingCustomerNotification(ctx context.Context, arg CreatePendingCustomerNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, createPendingCustomerNotification,
		arg.ID,
		arg.IdempotencyKey,
		arg.CorrelationKey,
		arg.CustomerID,
		arg.NotificationType,
		arg.NotificationChannel,
		arg.TemplateValues,
		arg.Status,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const existsCustomerNotificationByIdempotencyKey = `-- name: ExistsCustomerNotificationByIdempotencyKey :one
SELECT EXISTS (
    SELECT 1 FROM customer_notifications WHERE idempotency_key = $1
)
`

func (q *Queries) ExistsCustomerNotificationByIdempotencyKey(ctx context.Context, idempotencyKey string) (bool, error) {
	row := q.db.QueryRow(ctx, existsCustomerNotificationByIdempotencyKey, idempotencyKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markCustomerNotificationDispatched = `-- name: MarkCustomerNotificationDispatched :execrows
UPDATE customer_notifications
SET status = 'dispatched', dispatched_at = $2
WHERE id = $1
  AND status = 'pending'
`

type MarkCustomerNotificationDispatchedParams struct {
	ID           string             `json:"id"`
	DispatchedAt pgtype.Timestamptz `json:"dispatched_at"`
}

func (q *Queries) MarkCustomerNotificationDispatched(ctx context.Context, arg MarkCustomerNotificationDispatchedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCustomerNotificationDispatched, arg.ID, arg.DispatchedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markCustomerNotificationFailed = `-- name: MarkCustomerNotificationFailed :one
UPDATE customer_notifications
SET status = 'failed',
    failed_at = $2,
    failure_reason = $3,
    failure_message = $4
WHERE id = $1
  AND status IN ('pending', 'dispatched')
RETURNING correlation_key, idempotency_key, customer_id
`

type MarkCustomerNotificationFailedParams struct {
	ID             string             `json:"id"`
	FailedAt       pgtype.Timestamptz `json:"failed_at"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	FailureMessage pgtype.Text        `json:"failure_message"`
}

type MarkCustomerNotificationFailedRow struct {
	CorrelationKey string `json:"correlation_key"`
	IdempotencyKey string `json:"idempotency_key"`
	CustomerID     string `json:"customer_id"`
}

func (q *Queries) MarkCustomerNotificationFailed(ctx context.Context, arg MarkCustomerNotificationFailedParams) (MarkCustomerNotificationFailedRow, error) {
	row := q.db.QueryRow(ctx, markCustomerNotificationFailed,
		arg.ID,
		arg.FailedAt,
		arg.FailureReason,
		arg.FailureMessage,
	)
	var i MarkCustomerNotificationFailedRow
	err := row.Scan(&i.CorrelationKey, &i.IdempotencyKey, &i.CustomerID)
	return i, err
}

const markCustomerNotificationFailedBySMSGatewayMessageID = `-- name: MarkCustomerNotificationFailedBySMSGatewayMessageID :one
UPDATE customer_notifications
SET status = 'failed',
    failed_at = $2,
    failure_reason = $3,
    failure_message = $4
WHERE id = (
    SELECT customer_notification_id
    FROM customer_notification_sms_gateway_messages
    WHERE sms_gateway_message_id = $1
)
RETURNING correlation_key, idempotency_key, customer_id
`

type MarkCustomerNotificationFailedBySMSGatewayMessageIDParams struct {
	SmsGatewayMessageID string             `json:"sms_gateway_message_id"`
	FailedAt            pgtype.Timestamptz `json:"failed_at"`
	FailureReason       pgtype.Text        `json:"failure_reason"`
	FailureMessage      pgtype.Text        `json:"failure_message"`
}

type MarkCustomerNotificationFailedBySMSGatewayMessageIDRow struct {
	CorrelationKey string `json:"correlation_key"`
	IdempotencyKey string `json:"idempotency_key"`
	CustomerID     string `json:"customer_id"`
}

func (q *Queries) MarkCustomerNotificationFailedBySMSGatewayMessageID(ctx context.Context, arg MarkCustomerNotificationFailedBySMSGatewayMessageIDParams) (MarkCustomerNotificationFailedBySMSGatewayMessageIDRow, error) {
	row := q.db.QueryRow(ctx, markCustomerNotificationFailedBySMSGatewayMessageID,
		arg.SmsGatewayMessageID,
		arg.FailedAt,
		arg.FailureReason,
		arg.FailureMessage,
	)
	var i MarkCustomerNotificationFailedBySMSGatewayMessageIDRow
	err := row.Scan(&i.CorrelationKey, &i.IdempotencyKey, &i.CustomerID)
	return i, err
}

const markCustomerNotificationSentBySMSGatewayMessageID = `-- name: MarkCustomerNotificationSentBySMSGatewayMessageID :one
UPDATE customer_notifications
SET status = 'sent', sent_at = $2
WHERE id = (
    SELECT customer_notification_id
    FROM customer_notification_sms_gateway_messages
    WHERE sms_gateway_message_id = $1
)
RETURNING correlation_key, idempotency_key, customer_id
`

type MarkCustomerNotificationSentBySMSGatewayMessageIDParams struct {
	SmsGatewayMessageID string             `json:"sms_gateway_message_id"`
	SentAt              pgtype.Timestamptz `json:"sent_at"`
}

type MarkCustomerNotificationSentBySMSGatewayMessageIDRow struct {
	CorrelationKey string `json:"correlation_key"`
	IdempotencyKey string `json:"idempotency_key"`
	CustomerID     string `json:"customer_id"`
}

func (q *Queries) MarkCustomerNotificationSentBySMSGatewayMessageID(ctx context.Context, arg MarkCustomerNotificationSentBySMSGatewayMessageIDParams) (MarkCustomerNotificationSentBySMSGatewayMessageIDRow, error) {
	row := q.db.QueryRow(ctx, markCustomerNotificationSentBySMSGatewayMessageID, arg.SmsGatewayMessageID, arg.SentAt)
	var i MarkCustomerNotificationSentBySMSGatewayMessageIDRow
	err := row.Scan(&i.CorrelationKey, &i.IdempotencyKey, &i.CustomerID)
	return i, err
}

const saveSMSGatewayDispatch = `-- name: SaveSMSGatewayDispatch :exec
INSERT INTO customer_notification_sms_gateway_messages (
    id,
    customer_notification_id,
    sms_gateway_message_id,
    created_at
)
VALUES ($1, $2, $3, $4)
`

type SaveSMSGatewayDispatchParams struct {
	ID                     string             `json:"id"`
	CustomerNotificationID string             `json:"customer_notification_id"`
	SmsGatewayMessageID    string             `json:"sms_gateway_message_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SaveSMSGatewayDispatch(ctx context.Context, arg SaveSMSGatewayDispatchParams) error {
	_, err := q.db.Exec(ctx, saveSMSGatewayDispatch,
		arg.ID,
		arg.CustomerNotificationID,
		arg.SmsGatewayMessageID,
		arg.CreatedAt,
	)
	return err
}
