apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: beaesthetic-services
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - service: appointment
                  path: appointment/helm
                - service: customer
                  path: customer/helm
                - service: scheduler
                  path: scheduler/helm
                - service: notification
                  path: notification/helm
          - list:
              elements:
                - environment: dev
                  namespace: beaesthetic-dev
                  valuesFile: values-dev.yaml
                  targetRevision: HEAD
                - environment: prod
                  namespace: beaesthetic
                  valuesFile: values.yaml
                  targetRevision: HEAD
  template:
    metadata:
      name: "{{.service}}-{{.environment}}"
      labels:
        app.kubernetes.io/part-of: beaesthetic
        beaesthetic.io/environment: "{{.environment}}"
        beaesthetic.io/service: "{{.service}}"
        notifications.argoproj.io/subscribe.on-health-degraded.telegram: "-1004385477490" # beaesthetic monitoring channel
        notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1004385477490"
        notifications.argoproj.io/subscribe.on-sync-failed.telegram: "-1004385477490"
        notifications.argoproj.io/subscribe.on-deployed.telegram: "-1004385477490"
    spec:
      project: beaesthetic
      source:
        repoURL: https://github.com/beaesthetic/beaesthetic-backend.git
        targetRevision: "{{.targetRevision}}"
        path: "{{.path}}"
        helm:
          valueFiles:
            - values.yaml
            - "{{.valuesFile}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
