apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: beaesthetic-services
  namespace: argocd
spec:
  ignoreApplicationDifferences:
    - name: appointment-dev
      jsonPointers:
        - /spec/source/targetRevision
    - name: notification-dev
      jsonPointers:
        - /spec/source/targetRevision
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - service: appointment
                  path: appointment/helm
                - service: customer
                  path: customer/helm
                - service: scheduler
                  path: scheduler/helm
                - service: notification
                  path: notification/helm
          - list:
              elements:
                - environment: dev
                  namespace: beaesthetic-dev
                  valuesFile: values-dev.yaml
                  targetRevision: HEAD
                - environment: prod
                  namespace: beaesthetic
                  valuesFile: values.yaml
                  targetRevision: HEAD
  template:
    metadata:
      name: "{{.service}}-{{.environment}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        app.kubernetes.io/part-of: beaesthetic
        beaesthetic.io/environment: "{{.environment}}"
        beaesthetic.io/service: "{{.service}}"
    spec:
      project: beaesthetic
      source:
        repoURL: https://github.com/beaesthetic/beaesthetic-backend.git
        targetRevision: "{{.targetRevision}}"
        path: "{{.path}}"
        helm:
          valueFiles:
            - values.yaml
            - "{{.valuesFile}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{- if eq .environment "prod" }}
    metadata:
      annotations:
        notifications.argoproj.io/subscribe.on-health-degraded.telegram: "-1004385477490" # beaesthetic monitoring channel
        notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1004385477490"
        notifications.argoproj.io/subscribe.on-sync-failed.telegram: "-1004385477490"
        notifications.argoproj.io/subscribe.on-deployed.telegram: "-1004385477490"
    {{- end }}
    {{- if and (or (eq .service "appointment") (eq .service "notification")) (eq .environment "prod") }}
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
    {{- end }}
    {{- if and (or (eq .service "appointment") (eq .service "notification")) (eq .environment "dev") }}
    spec:
      source:
        helm:
          parameters:
            - name: image.tag
              value: $ARGOCD_APP_REVISION
    {{- end }}
