openapi: 3.0.0
info:
  title: SMS Gateway Webhook API
  description: |
    Welcome to the Customer API documentation. This API allows you to manage customer data, including creating, updating, searching, and retrieving customer records. It provides endpoints for various customer-related operations.
    
    ## Endpoints
    - **Get Customers**: Retrieve a list of customers with pagination support.
    - **Search Customers**: Search for customers by name or other criteria.
    - **Get Customer by ID**: Retrieve a customer's details by their unique ID.
    - **Create Customer**: Create a new customer record.
    - **Update Customer**: Update an existing customer's information.
    
    ## Request and Response Formats
    All requests and responses follow the JSON format. Please refer to the schemas section for detailed information on request and response payloads.
    
    ## Error Handling
    In case of errors, the API will respond with appropriate status codes and error messages. Refer to the error handling section for a list of possible errors and their meanings.
    
    ## Version
    This documentation covers version 1.0.0 of the Customer API.
  contact:
    email: petretiandrea@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://agenda.beaesthetic.it/notification-service/
paths:

  /sms-webhook/notify:
    post:
      tags:
        - sms-gateway
      operationId: smsGatewayNotify
      description: Webhook endpoint for sms gateway
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventNotificationDto'
      responses:
        '200':
          description: "Notification accepted"

components:
  schemas:
    AdditionalMetadata:
      type: object
      additionalProperties:
        type: string
    EventNotificationType:
      type: string
      enum:
        - message.deliver.succeeded
        - message.deliver.failed
    EventNotificationDto:
      type: object
      properties:
        eventType:
          $ref: '#/components/schemas/EventNotificationType'
        data:
          $ref: '#/components/schemas/SmsEntityResponse'
        metadata:
          $ref: '#/components/schemas/AdditionalMetadata'
    SmsEntityResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        content:
          type: string
        from:
          type: string
        to:
          type: string
        owner:
          type: string
          format: uuid
        isSent:
          type: boolean
        lastAttempt:
          type: object
          properties:
            attemptCount:
              type: integer
          oneOf:
            - $ref: '#/components/schemas/SuccessfulAttempt'
            - $ref: '#/components/schemas/FailedAttempt'
          discriminator:
            propertyName: type
            mapping:
              success: '#/components/schemas/SuccessfulAttempt'
              failure: '#/components/schemas/FailedAttempt'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - content
        - from
        - to
        - owner
        - isSent
        - createdAt
        - updatedAt
    FailedAttempt:
      type: object
      properties:
        type:
          type: string
          format: "failure"
        reason:
          type: string
          description: "Reason of failure attempt"
      required: [type]
    SuccessfulAttempt:
      type: object
      properties:
        type:
          type: string
          pattern: "success"
      required: [type]