syntax = "proto3";

package beaesthetic.notification.v1;

import "google/protobuf/struct.proto";

option go_package = "github.com/petretiandrea/beaesthetic-backend/core-contracts/notification;notification";

enum NotificationChannel {
  NOTIFICATION_CHANNEL_UNSPECIFIED = 0;
  NOTIFICATION_CHANNEL_SMS = 1;
  NOTIFICATION_CHANNEL_EMAIL = 2;
}

message CustomerNotificationRequested {
  string idempotency_key = 1 [json_name = "idempotencyKey"];
  repeated string customer_ids = 2 [json_name = "customerIds"];
  NotificationChannel notification_channel = 3 [json_name = "notificationChannel"];
  string notification_type = 4 [json_name = "notificationType"];
  google.protobuf.Struct body = 5 [json_name = "body"];
}

enum CustomerNotificationOutcomeStatus {
  CUSTOMER_NOTIFICATION_OUTCOME_STATUS_UNSPECIFIED = 0;
  CUSTOMER_NOTIFICATION_OUTCOME_STATUS_SENT = 1;
  CUSTOMER_NOTIFICATION_OUTCOME_STATUS_FAILED = 2;
}

message CustomerNotificationOutcome {
  string notification_id = 1 [json_name = "notificationId"];
  CustomerNotificationOutcomeStatus status = 2 [json_name = "status"];
  string reason = 3 [json_name = "reason"];
  string message = 4 [json_name = "message"];
  string idempotency_key = 5 [json_name = "idempotencyKey"];
  string customer_id = 6 [json_name = "customerId"];
}
